### ISSUE TITLE
Awesome App - Please add Search feature

### ISSUE THREAD

**Issue by eddo888** [bryceco/GoMap#137]
just needs a search feature and it is perfect

**Comment by geowOSM** [comment]
A search feature is already present but kind of hidden, a long press of the "arrow" in the status line will do the trick.

**Comment by eddo888** [comment]
cool thanks

**Comment by eddo888** [comment]
actually, that search is not working, no results found

**Comment by eddo888** [comment]
actually, that search is not working, no results found

**Comment by geowOSM** [comment]
> Wow, that is a well hidden feature :-)

Actually the "Nominatim search" is hidden in the Help under "Locate landmarks" ;-)

**Comment by fntagit** [comment]
Is there a way to find an object by its OSM identifier?

**Comment by bryceco** [comment]
No. Do other editors support lookup by identifier?

**Comment by fntagit** [comment]
Well, if a fellow mapper sends me a request to inspect a given element, I just access it on the OSM site by entering, for example, https://www.openstreetmap.org/relation/3080558. This shows and selects the item on the map. I can then just click 'Modify' if I need to modify it. So, while the editor itself does not, strictly speaking, support lookup by identifier, the functionality is available and seamless, because it is part of the OSM web experience.

**Comment by dieterdreist** [comment]
sent from a phone

> On 25. Aug 2018, at 21:36, bryceco <notifications@github.com> wrote:
> 
> No. Do other editors support lookup by identifier?
> 


in Josm you can download single objects by their type and id, or you can search for them with the search function.

**Comment by fishsunsun** [comment]
I would say searching a specific type of POI that **_confined only_** in the map currently viewing.

**Comment by bryceco** [comment]
I'm closing this because there doesn't seem to be any consensus about what the new feature would be. Feel free to make a specific suggestion and re-open.
