### ISSUE TITLE
Make the "note", "description", "source", "inscription" key a textarea

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#141]
Right now the "note" key has a string as value filed (one line of text).

But the "note" key is often used for text that is multiple lines".

It would be great to have it show up as a textarea / field with multiple lines.

Screenshot:

![img_9112](https://user-images.githubusercontent.com/111561/43704534-2d4b5e86-9960-11e8-8269-2dee6f64d468.jpg)

**Comment by wtimme** [comment]
Improving (multi-line) text input is something that we could tackle in a more general way. On text area that comes into mind is the one for the commit message, another one would be the "diff" for the changelog. They can be worked with, sure, but the more text they contain, the less pleasant it is to do so.

Instead of in-place editing, how do you guys feel about a new view controller that has the sole purpose of editing longer text?

**Comment by bryceco** [comment]
We want the text to be readable without an extra click, so I think we need to have the edit box expand automatically.

**Comment by tordans** [comment]
I know nothing about the technical complexity, so solely as a user is say: Read and Write should be both in the same view. 

Cases like the commit message and the "All Tags" section should have fields that I can just tab in and start typing without any context switch / reorientation to a new view. In the case of the commit message the whole screen only has this purpose, so another layer would feel too much.

**Comment by TheAdventurer64** [comment]
@wtimme

**Comment by tordans** [comment]
I added a few more key to the title, to clarify this request is about more than the "notes" key. Memorials have the "inscription" key for example", which would also be a great candidate. 

UseCase: Since "Stolpersteine" (https://wiki.openstreetmap.org/wiki/DE:Stolpersteine) are best mapped on the go, GoMap is a great app for that; but navigating the long line is really time consuming and tedious.

**Comment by bryceco** [comment]
Fixed in cb7e2954f73c6e12891c806e2074e7982810f3f8
