### ISSUE TITLE
Navigating relations

### ISSUE THREAD

**Issue by fntagit** [bryceco/GoMap#144]
When an object is selected on the map, the "All Tags" panel lists the relations containing that object, if any. From there, one can navigate "up" to the information panel of any relation listed. If a relation is contained in another relation, one can continue to navigate "up".
When the "All Tags" panel for a relation is active, the members of that relation are listed, but it does not seem possible to navigate "down" to one of its members.
To fully explore relations, I would find it useful to be able to navigate "down" from a relation to any of its members, with the idea that, when tapping "Cancel", the currently displayed object would be selected on the map.

**Comment by dieterdreist** [comment]
it would also be nice to get more information about the members. Currently it only reads “(way)”, maybe it could rather show “w1234567” (where 1234567 is the osm id), or maybe the name and if there isn’t, the note or description, and otherwise the id.

**Comment by fntagit** [comment]
What version are you using ? Here, I see the name if one exists, otherwise "node" <id> or "way" <id>.

**Comment by fntagit** [comment]
Ah, looking at more relations, I did find occurences of "(way)" for ways that have no tags at all. Sometimes, one encounter long lists of identically looking members. So I wonder if it would not make sense, given the fact that a relation is by definition an ordered list, to number the lines. Well, it is certainly not easy for a software developper to please everybody 8-).

**Comment by dieterdreist** [comment]
sent from a phone

> On 25. Aug 2018, at 16:29, fntagit <notifications@github.com> wrote:
> 
> What version are you using ? Here, I see the name if one exists, otherwise "node" or "way" .


yes, multipolygons often consist of ways without names, sometimes they have other tags (barrier, boundary, etc.) but often even not. Seeing the id would help to identify them more easily.

**Comment by tordans** [comment]
To make this issue more actionable, I will try to summarise the feature request. Is this a good list to handle this issue?

- [ ] "When the "All Tags" panel for a relation is active, the members of that relation are listed, but it does not seem possible to navigate "down" to one of its members. To fully explore relations, I would find it useful to be able to navigate "down" from a relation to any of its members (…)"
  - Screenshot: This is visible in "Example Building", where there could be a link to the outer/inner member
  - Screenshot: Members in "Route" and "Route Master"

- [x] "…with the idea that, when tapping "Cancel", the currently displayed object would be selected on the map." – This is IMO already done, see "after "cancel" from route master"

- [ ] "it would also be nice to get more information about the members. Currently it only reads “(way)”, maybe it could rather show “w1234567” (where 1234567 is the osm id), or maybe the name and if there isn’t, the note or description, and otherwise the id."
  - Screenshot: This is visible in "Example Building", where "(way)" could be "w213"

- [ ] I wonder, how a "go back" / "go forward" UI should look like for this. Once I browse a layer up/down, how to get back to where I came from. Right now I can only "cancel" and start from the beginning. – Is it maybe possible to layer the panels on top of eachother, so I only "cancel" the top most layer? 
  - Screenshot: How to get back from "route master" to "route" to "all tags"

# Example Building

Link: https://www.openstreetmap.org/relation/933526

Starting Point | All Tags
--- | --- 
![building selected](https://user-images.githubusercontent.com/111561/76690162-c3120e00-663d-11ea-9668-77a8868135a0.jpeg) | ![building relation](https://user-images.githubusercontent.com/111561/76690168-cf966680-663d-11ea-92ed-597379fbdb18.jpg)

# Example Bus Platform

Link: https://www.openstreetmap.org/way/381784481

Starting Point | All Tags | Route | Route Master | after "cancel" from route master
--- | ---  | ---  | ---  | --- 
![bus platform selected](https://user-images.githubusercontent.com/111561/76690232-77ac2f80-663e-11ea-9980-5b6e2a188349.jpg) | ![bus platform all tags](https://user-images.githubusercontent.com/111561/76690238-809d0100-663e-11ea-9fbe-61238b95126a.jpg) | ![bus route tags](https://user-images.githubusercontent.com/111561/76690247-96122b00-663e-11ea-9606-1b2737321113.jpg) | ![bus route master](https://user-images.githubusercontent.com/111561/76690250-9f02fc80-663e-11ea-8435-d1d4d319d5f7.jpg) | ![bus rel selected](https://user-images.githubusercontent.com/111561/76690255-a9bd9180-663e-11ea-8349-69c22534ae68.jpg)

**Comment by bryceco** [comment]
The latest TestFlight build has better descriptions for members and allows you to jump to a member by selecting it.

For a large relation it’s likely that some (or most) members haven’t been downloaded, and it’s only possible to navigate to previously downloaded members. Those members will have a “>” icon indicating they’re available.
