### ISSUE TITLE
Multilingual descriptions and possible presets from wiki

### ISSUE THREAD

**Issue by nyurik** [bryceco/GoMap#149]
Hi, just in case you haven't seen it, there is a project to put all documentation in a machine readable format on the wikibase that runs on the osm wiki.  iD editor [may start using it soon](https://github.com/openstreetmap/iD/issues/5321) as well.

See [project description with examples](https://wiki.openstreetmap.org/wiki/OpenStreetMap:Wikibase).

Also, since you recently worked with the presets, could you help moving them into the new system too? This way you will be able to quickly download the latest ones from the community, and they could be centrally managed and usable by all of the editors. Thanks!

**Comment by bryceco** [comment]
Wikibase is something I fully support, and using it would potentially solve some issues with using the iD presets as I currently do. For me to adopt it it needs to:
* have coverage comparable to what the iD presets currently have, and 
* be available as an offline database since my app doesn't assume internet is available.

Are you wanting to do a bulk import of the iD presets into Wikibase? The most important information in the presets database is mapping a geometry to a set of potential features (a way might be a highway, fence, etc), and the tags that are most commonly associated once a particular feature is selected (e.g. a highway often has a surface=*). And these choices need to be ordered in a logical manner, such as by popularity, alphabetically, etc depending on the key. 

There are also certain key combinations with special meaning: The "driveway" feature is a highway=service, service=driveway pair. The user needs to be able to select a single feature in the UI and have both keys set automatically.

It isn't clear to me how that information will be structured and accessed.

**Comment by bryceco** [comment]
The iD structure is to define features, such as “Nail Salon”, and a feature has mandatory tags (shop=beauty,beauty=nails) that uniquely identify it. Then that feature has an associated set of presets that are useful to combine with it, such as name, address, opening hours, etc. And then each preset has one or more tags or tag/value pairs that are presented to the user to fill in. For example the Address preset contains city/street/house/zipcode tags, grouped as a single preset. (Also Address uses locale info to not ask for zipcode in countries that don’t use it, etc).

So under the shop=beauty tag definition you sould have a table of associated features, containing columns with:
* the tags/values that uniquely identify the feature
* the name of the feature (multilingual)
* a list of preset identifiers associated with that feature 

Then for tags like addr:street you need to indicate to which preset(s) it belongs.

**Comment by nyurik** [comment]
@bryceco thx, seems reasonable in the Wikibase structure:

Preset is a wikibase item with
* instance-of = feature
* requires = [ tags / keys / other presets ]
  * may have multiple values
  * each value could have a qualifier that limits its scope, e.g. "only needed for region", or "anywhere except that region"
* suggested / recommended / ...  -- other properties similar in structure to `requires`

Would that work?

**Comment by nyurik** [comment]
P.S. Try modeling a complex item this way in the wikibase. I just created a [preset item](https://wiki.openstreetmap.org/wiki/Item:Q7564), so just use the [create new item](https://wiki.openstreetmap.org/wiki/Special:NewItem) special page to create some complex feature, set instance of to Q7546, and use [properties](https://wiki.openstreetmap.org/wiki/Special:ListProperties) to describe it.  I think it should be enough to create a few example preset items to see how they would look like, and start the discussion.

**Comment by bryceco** [comment]
I created a Surface item but I don’t see any way to set instance-of or properties.

**Comment by nyurik** [comment]
on the right side at the bottom, click "add statement", type "instance of", and enter q7564 as a value (or you type words and hope it will find it ;)).  That's how you add all aspects of the item.

**Comment by nyurik** [comment]
P.S. that link only appears after the page is fully loaded

**Comment by bryceco** [comment]
Oh, the site is busted on iPad/Safari. It looks different when I reload as desktop site.

**Comment by nyurik** [comment]
Could you check if you see the same problem at https://www.wikidata.org/wiki/Q42  ?   If so, you may want to create an issue at the http://phabricator.wikimedia.org/

**Comment by tordans** [comment]
Just for reference, this topic is also discussed at https://wiki.openstreetmap.org/wiki/OpenStreetMap_talk:Wikibase#Presets; I answered there.

**Comment by bryceco** [comment]
While I fully support the wikibase idea, it seems a long ways from what iD and GoMap require at this point. And the web interface is too confusing for me to investigate it in-depth. If anyone involved will be in Detroit next week and wants to discuss we can get together with Bryan and iron it out.

**Comment by nyurik** [comment]
@bryceco i wish i could go to Detroit, but I had a scheduling conflict with another conference.  How about we sync up over a video chat in the next few days?  The best time for me is between 9pm-12pm London time. Email YuriAstrakhan at gmail.

**Comment by bryceco** [comment]
Closing for lack of interest.
