### ISSUE TITLE
Set "source:height" with the height

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#159]
There is a `source:height=*` attribute, see https://wiki.openstreetmap.org/wiki/Key:height#Sources

It would be nice to have this set automatically whenever I choose "set height" via the height-measurement-tool.

Maybe something like

> source:height=Go Map!! in-app measurement feature

Update: `source:height` is used ~9,800 times with ~320 values. (https://taginfo.openstreetmap.org/keys/source%3Aheight).

**Comment by zlavergne** [comment]
I may be a little late to this discussion but tagging the `source=*` on the changeset seems to be the [preferred way](https://wiki.openstreetmap.org/wiki/Key:source) now. The namespaced source you suggested is what they refer to as "historical". 

Unfortunately, there isn't an alternative to tell the source of individual tags for an object in a changeset because you can't make a connection to a singular object from the changeset(unless it was a 1 object changeset). IMO there needs to be more tooling and/or an update in the changeset table of the db to allow for an object/changeset relationship.

**Comment by tordans** [comment]
I think we can close this for the same reasons as https://github.com/bryceco/GoMap/issues/188#issuecomment-481389349
