### ISSUE TITLE
Add support for development using Swift

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#165]
> As a developer, I want to be able to use Swift when contributing to the project, so that I can leverage all of its advantages.

I propose to configure the project in a way that allows for the development using Swift and makes Objective-C code available to Swift (e. g. by auditing headers for nullability).

In #155, @bryceco commented that

> There are several big issues with converting to Swift, ask before you start

What kind of issues are there? I miss Swift with every Objective-C line that I write. 😢

**Comment by bryceco** [comment]
Adding nullability to headers is fine. I'd prefer that there was an actual swift class somewhere in the app to justify this, either new or converted, rather than doing it just because we can.

The holy grail of converting to Swift would be to eliminate OsmNode/OsmWay/OsmRelation being derived from NSObject, which would eliminate a lot of reference counting overhead that forces the use of C++ in several situations.

The show stopper for converting to Swift is the undo manager. Currently it archives undo/redo actions by converting selectors to/from strings, and using NSInvocation to call them later. None of that works in Swift. The undo manager needs to be rewritten to save/restore old/new copies of modified objects instead of unplaying/replaying sequences of selector invocations.

**Comment by wtimme** [comment]
> The holy grail of converting to Swift would be to eliminate OsmNode/OsmWay/OsmRelation being derived from NSObject, which would eliminate a lot of reference counting overhead that forces the use of C++ in several situations.

May I shamelessly plug [SwiftOverpassWrapper][1]? It's another OSM-related project that I contribute to. It already has [Node][2], [Way][3] and [Relation][4] covered and comes with an XML parser for OSM XML, the latter being [covered by unit tests][5].

> The show stopper for converting to Swift is the undo manager.

There will probably be more than one place in which getting Objective-C and Swift to play along nicely requires some extra effort. I'm not saying we should go ahead and rewrite everything. Rather, I suggest we start setting up the minimum requirements (e. g. bridging headers) so that one _could_ start adding Swift files.

[1]: https://github.com/holyturt/SwiftOverpassWrapper
[2]: https://github.com/holyturt/SwiftOverpassWrapper/blob/master/SwiftOverpass/Models/Elements/OverpassNode.swift#L13
[3]: https://github.com/holyturt/SwiftOverpassWrapper/blob/master/SwiftOverpass/Models/Elements/OverpassWay.swift#L13
[4]: https://github.com/holyturt/SwiftOverpassWrapper/blob/master/SwiftOverpass/Models/Elements/OverpassRelation.swift#L14
[5]: https://github.com/holyturt/SwiftOverpassWrapper/tree/master/SwiftOverpassTests/Extensions

**Comment by wtimme** [comment]
With #178 merged, it is possible now to use Swift when creating new files.
