### ISSUE TITLE
Add new node and directly open "POI Type" selection when long-tapping the "Add Button"

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#203]
> As a user, I want to add new nodes in as less steps as possible, so that I can save time and taps.

## Acceptance criterias

When no object is selected and the user performs a long-tap gesture on the "Add Button", the "POI Type" selection is opened as if the they had done the following steps manually:

1. Tap "Add Button"
2. Tap "Tags"
3. Tap "Type"

After selecting a POI type, the user is taken back to the "Common Tags" screen, where they can add additional properties for the new node.

When deciding _not_ to add an object (tapping the back button "Common Tags" in the "POI Type" selection and then tapping "Cancel" in the top-left corner), no "(new object)" is added to the map. Instead, the user is back on the map as if they did not long-tap on the "Add Button".

**Comment by bryceco** [comment]
The extra taps are often frustrating to me also, this seems like a good solution.

**Comment by tordans** [comment]
I wanted to write such a tickets a few times :-).

I wonder, if we can be more radical.
IMO the Type-Selection is the dominent usecase. So it should be the default action.
Only as a second step, we could lead the user to the "all tags"-screen which is, what you need to add a non-preset-tag.

**So usecase: Add tag with type**
1. Tap "Add Button" (like before: user is on map with placeholder tag)
2. Tab "Tags" (user is on POI Type list)
3. Tab POI Type or click search field for keyboard

From step 3, other usecases can start. Especially:

**So usecase: Add tag with raw tags**
4. Tab "All Tags" (bottom) or "Common Tags" to access the manual tagging.
(That is why for (3) its important not to open the keyboard right way, which otherwise where best.)

One thing this processes looses: right now the UI remembers the last panel I used to add tags. To be easier to understand this should go away in favor of the same tab-order every time. However, it further puts pain on the second use case.

This idea only makes sense if we agree, that using the POI Type screen really is the default tab order.

--- 

In case this is to radical, here is another idea:

**So usecase: Add tag with type**

1. Long-Tap "Add Button" => User is on POI Type selection with the search keyboard out.

No need to "Tap "Tags"", we can just long-tab the first action, right?

For all other usecases, nothing changes.

**Comment by dieterdreist** [comment]
sent from a phone

> On 14. Apr 2019, at 08:39, Tobias <notifications@github.com> wrote:
> 
> I wonder, if we can be more radical.
> IMO the Type-Selection is the dominent usecase. So it should be the default action.
> Only as a second step, we could lead the user to the "all tags"-screen which is, what you need to add a non-preset-tag.


maybe this could become a user setting (common tags or all tags as default)? 
I am using go map!! for years but never (maybe 2 times) used the default tags view, I always use all tags and liked the freedom go map!! offers by not requiring the use of presets.

**Comment by tordans** [comment]
Thanks @dieterdreist, that makes my first suggestion obsolete.

@wtimme what are your thoughts on my second idea?

> Long-Tap "Add Button" => User is on POI Type selection with the search keyboard out.
>No need to "Tap "Tags"", we can just long-tab the first action, right?

--- 

Also, as a reminder: Should this feature change, we need to also update the help page.

**Comment by wtimme** [comment]
Sounds good. 👍🏼

I've pushed a branch in which long-tapping on the "Add button" is already working for when no element is selected. Handling of long-taps while something is selected has still to be added, though. If anyone wants to participate, feel free to checkout the code.

**Comment by bryceco** [comment]
Cool. I’m traveling (iPhone only, no laptop) until the end of April. Is there a way I can view a diff of your branch using the GitHub website?

**Comment by wtimme** [comment]
Sure, [here you go][1].

[1]: https://github.com/bryceco/GoMap/compare/master...wtimme:feature/203-Show-POI-type-search-when-long-tapping-add-button

**Comment by bryceco** [comment]
I took a look at this branch and realized that it conflicts with a related gesture: if you press and hold the + button you can tap the screen repeatedly with a second finger to drop nodes very quickly (for drawing ways).

**Comment by tordans** [comment]
> related gesture: if you press and hold the + button you can tap the screen repeatedly with a second finger to drop nodes very quickly (for drawing ways).

Oh, I was not aware of this. Will try it out :).

But I wonder, if there is a simpler way to tackle this issue. Since its was created, most of the Default-Common-Tags where removed, so the Common-Tags-Screen is nearly blank in its initial state (Type + Name + Customize Presets).

How about, whenever I add a node (+ => Tags) the UI opens in the POI-Type-Screen?
From there I can switch to the all tags via the button on the bottom bar. And back to the common-tags-screen via the back button (top right) and the bottom bar-button.

(As far as I remember the tags UI also remembers, if I was using the all tags screen the last time; this does not need to change).

This would still save me one click, which is also an inconvenient click since the action is at the top of the screen which is hard to reach with one hand usage.

**Comment by bryceco** [comment]
Yes I agree that going straight to the search box for brand new nodes would be better now.

**Comment by dieterdreist** [comment]
writing about notes, IMHO there is an UI fail here, because it happened multiple times that I canceled the note creation rather than submitting the note (which I wanted to do). 
It’s the position of the cancel button on the top right, where in tags you have “save” but in notes its cancel. Please move this to the left corner and maybe add a duplicate “save”/comment/submit button up right. (generally, “submit” would seem better than “comment” for the creation of a note)

**Comment by tordans** [comment]
> Yes I agree that going straight to the search box for brand new nodes would be better now.

I used the testflight for a few days now, thanks a lot! The new UI is a lot better. But I still struggle with switching between "common tags" and "all tags". In my mapping, I use both "pages" all the time and I find myself switching a lot.

Suggestion: Add a swipe gesture that allows for a quick change between the two.
1. open new node
2. see "all tags" view with keyboard
3. swipe in content view from left to right
4. see the "common tags" view (ideally with an active preset-select if none is selected yet)

Same for the swipe "right to left" for the other way around.

I think of this the same way as closing a panel from top to bottom.

Another solution would be to merge the two views, but that requires more planning and thinking :).

**Comment by dieterdreist** [comment]
Personally, I am rarely using the presets tab (sometimes for addresses), but what I would really appreciate: if there would be a button on the "all tags" tab to add an address template (like in presets, fields for street, housenumber, postcode, city and eventually more). 

It would be _nice to have_ a row of buttons in the all tabs view, with custom presets (a button which adds a list of keys and/or values (textfield, or single or list to choose if there are several possibilities) which you have defined yourself, plus eventually a filter which determines when the custom preset button is shown (presence of tags or combinations of tags, e.g. shop=* or amenity in (restaurant, fast_food, pub, cafe) )). I know there are already custom presets, but they are not accessible from the general tabs button (in autocompletio they are there I think, but not sure).

For example I'd like to have a preset that sets "amenity=drinking_water and fountain=nasone" on the same object. Or add "ref:vatin=*" to any object. In the latter case, it would also make sense to have a simple check (number of digits of the value, and whether the first two are capitalized letters). Another combination would be amenity=recycling, defining it also as "container" and "for clothes". I am sure, everybody has some common combinations which they use so often that a personal preset would make sense.

This is the maximum feature description, the "wish you everything" version, of course it could start much smaller ;-) Thanks for your fantastic work!

**Comment by TheAdventurer64** [comment]
> Personally, I am rarely using the presets tab (sometimes for addresses), but what I would really appreciate: if there would be a button on the "all tags" tab to add an address template (like in presets, fields for street, housenumber, postcode, city and eventually more).
> 
> It would be _nice to have_ a row of buttons in the all tabs view, with custom presets (a button which adds a list of keys and/or values (textfield, or single or list to choose if there are several possibilities) which you have defined yourself, plus eventually a filter which determines when the custom preset button is shown (presence of tags or combinations of tags, e.g. shop=* or amenity in (restaurant, fast_food, pub, cafe) )).
> 
> I know there are already custom presets, but they are not accessible from the general tags tab (in autocompletion they are there I think, but not sure), and while it can be filtered when they should be automaticatically displayed, it should allow for combinations (e.g. amenity= and / or shop=*) in the filter, and for setting multiple tags at the same time.
> 
> For example I'd like to have a preset that sets "amenity=drinking_water and fountain=nasone" ohttps://help.github.com/articles/github-community-guidelinesn the same object. Or add "ref:vatin=*" to any object. In the latter case, it would also make sense to have a simple check (number of digits of the value, and whether the first two are capitalized letters). Another combination would be amenity=recycling, defining it also as "container" and "for clothes". I am sure, everybody has some common combinations which they use so often that a personal preset would make sense.
> 
> This is the maximum feature description, the "wish you everything" version, of course it could start much smaller ;-) Thanks for your fantastic work!

I agree. I may stop using JOSM and work on Go Map!! more if this issue  was resolved.
