### ISSUE TITLE
Display app version number on the settings page

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#210]
For some reason I never remember to look at the info-(i)-panel on the map for the version number. Instead I go to settings and create an email draft which shows the version number.

So I wonder if there is another place where the version could be displayed.
- For example as a small font on the end of the settings-page?
- Or maybe in the button "Bug Report & Suggestions for v 1.6.2"

PS: This is similar to https://github.com/bryceco/GoMap/issues/28, but for another place.

**Comment by bryceco** [comment]
I’d like the version at the top of the settings without a section header. Is that possible?

**Comment by wtimme** [comment]
Since this settings is not as important to the "regular" user as say, the OSM login credentials, I think putting it at the bottom is a good compromise. I've seen that in a few apps, and always liked to have some geeky statistics and data. How about we put
- Version number
- Build number
- Configuration (DEBUG, RELEASE)
- Commit hash

there? The latter might be the most unimportant, but sometimes it might help pin down the source of a problem.

**Comment by wtimme** [comment]
This turns out to be easy to implement: We just need to return the information in `SettingsViewController`, `tableView(_:titleForFooterInSection:)`:

![version-in-settings](https://user-images.githubusercontent.com/1681085/56245697-93563100-608f-11e9-9e99-bb8e266d22ac.png)

Looks like the build number (`CFBundleVersion`) is the same as the version (`CFBundleShortVersionString`). What do you think - does it add any value to show this?

As for the commit hash, I came across [some answer on Stackoverflow][1] in which they use some build run scripts. In the comments, it seems like the behaviour changed with some older Xcode version. I don't know how stable that approach is. Does someone have experience with this?

[1]: https://stackoverflow.com/a/26539917

**Comment by bryceco** [comment]
What you have looks great. I don’t think commit hash is necessary.

**Comment by wtimme** [comment]
This issue can probably be closed, right?

**Comment by zlavergne** [comment]
@wtimme if you say something like `Closes #210` in your PR message, it will automatically close the issue. You can find more info about the keywords [here](https://help.github.com/en/articles/closing-issues-using-keywords)

**Comment by wtimme** [comment]
Hehe, thanks, I only realized this after I pushed. 😅 I'll try to do this next the next time I work on a branch.
