### ISSUE TITLE
enable remote control

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#235]
Would it be complicated to have goMap work with the osm.org remotecontrol feature? Has it to do with #164 ?

**Comment by wtimme** [comment]
Hey @dieterdreist, I just had a quick look at the JavaScript on osm.org. Looks like it uses an iFrame with the address `http://127.0.0.1:8111/load_and_zoom?`. From the [documentation of JOSM][1] it looks like JSOM runs a local server at port 8111 and listens for these calls. From my experience, this is not the way websites interact with apps. Rather, they use deeplinks (e. g. `osm://load_and_zoom?`, where the app registers itself as a handler for `osm://`) or an associated domain (#164), the latter which is Apple's preferred way of handling this scenario.

[1]: https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands

**Comment by dieterdreist** [comment]
Thank you, @wtimme 
If I recall correctly, some time ago Bryce had asked over at website@osm whether they would be willing to put something on the site so that it became an associated domain.

I have found this https://github.com/openstreetmap/openstreetmap-website/issues/985
(maybe not helpful, but related), and of course this: https://github.com/openstreetmap/openstreetmap-website/pull/1478

**Comment by wtimme** [comment]
I did some more digging, and noticed that with openstreetmap/openstreetmap-website#994, the `geo:` share link was introduced. As far as I can tell, it allows the sharing of the map's current center coordinate as well as the zoom level. In the Simulator, the URL was passed to GoMap and parsed correctly.

Since personally, I am using either GoMap on my iOS device _or_ iD on my MacBook, I don't know exactly what the usecase of the "enable remote control" feature is. Could you briefly outline how you would use this? That would help me understand better what is required here. Thanks in advance for your effort!

**Comment by dieterdreist** [comment]
The remote control lets you edit the part of the map you are looking at in OpenStreetMap.org
It is a convenience feature so you can fix problems you notice while looking at the map or a feature in the map.
Naturally, edit with GoMap!! would only make sense if you’re on iOS and have the app installed

**Comment by bryceco** [comment]
#164 is the way forward on this issue.
