### ISSUE TITLE
Icons missing since preset update

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#263]
I've merged the recent changes into my fork and released a new Beta.

@tordans sent me feedback that the icons were missing. I took a look at the `master` and noticed that, indeed, the icons are missing. Take a look:

![Screenshot of the current state of `master`](https://user-images.githubusercontent.com/1681085/75390480-3ac30780-58e0-11ea-8b21-d730f456a079.png)

After reverting bryceco/GoMap@fcdb717, I was able to see the icons again:

![icons-gomap-reverted](https://user-images.githubusercontent.com/1681085/75390487-3dbdf800-58e0-11ea-8aef-9b2b51f9a892.png)

**Comment by bryceco** [comment]
Since the last pull of presets iD changed the way they reference icons, which is great except that we don't support it yet. If you look at the "icon" section of https://github.com/openstreetmap/iD/blob/2.x/data/presets/README.md it has a description of the new nomenclature which should guide the work that needs to be done.

**Comment by wtimme** [comment]
Sounds good. Should we temporarily revert the change until someone has time to implement a proper fix?

**Comment by bryceco** [comment]
I just pushed a fix for the maki- icons. There should be a more general icon pass that imports the other icons iD has added and adds our own support for them.

**Comment by wtimme** [comment]
Thanks! Do you have a reference to the commit? I wanted to take a look in order to understand how the icons are being named, but I am not able to find the changes in `master`.
