### ISSUE TITLE
Upload screen should have a section for if people want their edits checked

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#350]

**Comment by tordans** [comment]
As far as I know, this feature is not really well supported in the community ATM, so I am not sure if it will really be useful.

The way I remember it is: This is a changeset-tag that was introduced by ID. However, there are no clear processes for those changesets set up for everything that needs to happen after clicking & saving it. So the user experience is not ideal: The UI suggest that someone will checkt it, when in fact its likely that no one ever will. And since there is no special tooling for it, its hard to get into checking those changesets. For example, there is no tool to mark a changesets as „I checked it it looks good“ – apart from leaving a comment. And there is no „those changesets still need checking“ or „subscribe to changesets that need checking in my area“ – and so on.

There was a evaluation in a few osm user-blogposts about the usage and response of the feature a while back; I can look them up if you are interested.

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. Jul 2020, at 09:53, Tobias <notifications@github.com> wrote:
> 
> For example, there is no tool to mark a changesets as „I checked it it looks good“ – apart from leaving a comment.


AFAIR you can mark changesets in osmcha, but you’re right as it isn’t a service from the OpenStreetMap-Foundation nor is it integrated into the OpenStreetMap website

**Comment by TheAdventurer64** [comment]
> As far as I know, this feature is not really well supported in the community ATM, so I am not sure if it will really be useful.
> 
> The way I remember it is: This is a changeset-tag that was introduced by ID. However, there are no clear processes for those changesets set up for everything that needs to happen after clicking & saving it. So the user experience is not ideal: The UI suggest that someone will checkt it, when in fact its likely that no one ever will. And since there is no special tooling for it, its hard to get into checking those changesets. For example, there is no tool to mark a changesets as „I checked it it looks good“ – apart from leaving a comment. And there is no „those changesets still need checking“ or „subscribe to changesets that need checking in my area“ – and so on.
> 
> There was a evaluation in a few osm user-blogposts about the usage and response of the feature a while back; I can look them up if you are interested.

Sure.

**Comment by bryceco** [comment]
Great feedback. Sounds like this feature is something we should consider once users can have a reasonable expectation the app delivers on the promise.
