### ISSUE TITLE
Idea: Go Map!! UI Overhall

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#358]
It’s been a while since Go Map!! had a UI overhall. I propose that we update the UI to something like this:
![D13811C0-C3E6-43B9-A811-4878871DC59D](https://user-images.githubusercontent.com/50059322/86343320-8110d600-bbf4-11ea-86a7-4823f9ed2194.jpeg)

**Comment by bryceco** [comment]
I’ve been contemplating that idea as well, having the buttons floating over the map and discarding the toolbar. It would allow the + button to be a much larger target

**Comment by mormahr** [comment]
This is a quick sketch. It's focussed on being more minimal and welcoming to beginners, with progressive disclosure of elements. When i started using this app i was confused about the multiple settings / options buttons and to be honest, i still am. The icons are also a little ambiguous, but i haven't looked into those. I'd like to submit some ideas about settings structure and general navigation if i find some time. Note that the icons in this sketch aren't properly sized and positioned and are more like placeholders, it's more about the general structure. Most of the elements are inspired by the native Apple Maps app.

### + / Add Action

My idea is to add a draggable `+` button, that can be dropped onto the map, so you can do a quick thumb "swipe" to the intended position. If you tap it, it creates a node in the center of the map, just like it's done currently.

Another option would be that it could be like the twitter app and offer multiple options when dragging.

I also want to explore removing the intermediate step of "Tags" / "Add Note" with a unified modal or something like that.

### Dragging a node

I'm not yet sure about this one. I feel like it's unintuitive to drag a node by the arrow glyph instead of on the node itself, but i also see why it's done like that. Maybe a magnifying view (like the old iOS cursor) to aid in positioning would work, but i haven't really put to much thought into this yet. This would go hand in with the add action.

![Go Map!! Main UI](https://user-images.githubusercontent.com/7482056/87154092-df0a8100-c2b8-11ea-9662-950ebd85bc66.png)

**Comment by mormahr** [comment]
How long do you intend to keep the iOS 9 minimum deployment target? That will probably make some changes a lot more work.

**Comment by bryceco** [comment]
I plan to do one more release that supports iOS 9, so by end of this month we can bump it to iOS 10. 

I think this more minimal presentation looks pretty good, and hiding elements until needed is a good idea. 

There are currently two settings buttons, which I agree is a little bit confusing. The Display Settings button configures everything related to the appearance of the map, and I use it fairly frequently. For example changing the aerial photography background is something that I wouldn’t want to be any more cumbersome to access. 

The General Settings button controls everything non-map related, and is less frequently used. But I also want to avoid have a large hierarchy of menus in settings, which makes things difficult to discover. 

The idea of dragging + to create a node is pretty interesting, but I would like to see how it works for extending ways as well as creating initial nodes. 

Dragging with the label (not just the move glyph) is probably here to stay. Dragging the node directly is too difficult to position accurately. Making the action more obvious is where we should make improvements.

**Comment by TheAdventurer64** [comment]
#380

**Comment by bryceco** [comment]
@mormahr You're mockup and suggestions here are really valuable. Please let me know your thoughts on the current beta either here or in #380. I plan to incorporate your suggestion of hiding UI elements until needed once we've nailed down the layout.

**Comment by bryceco** [comment]
Closing this as discussion has moved to #380
