### ISSUE TITLE
Increased Swift usage

### ISSUE THREAD

**Issue by mormahr** [bryceco/GoMap#367]
I'm starting to learn the codebase, as i want to contribute some features (e.g. keyboard shortcuts and cursor support, maybe future UI changes). I noticed mixed usage of Swift and Obj-C and was wondering if you're open to increased Swift usage? If you are I'd like to submit some PRs slowly porting over single classes / topics. After some time this would also allow to use more "swifty" language features.

I think the benefit would be, that Swift is pushed pretty hard at the moment and most newcomers are learning Swift instead of Obj-C. Some new APIs are also Swift only. Since Swift is now ABI stable and the language has matured to a large extend, i think the time to port over some existing code is right.

I'd probably start with small ViewControllers, specifically the ones where i'd like to implement keyboard shortcut support. But i'm also open to suggestions.

**Comment by mormahr** [comment]
While trying this i had problems with the `#if TARGET_OS_IPHONE` conditionals. [So _if_ the Mac specific code would be removed](https://github.com/bryceco/GoMap/issues/156#issuecomment-657575526), then porting should probably wait till after that.

**Comment by bryceco** [comment]
Its fine to write new code, or rewrite old code, in Swift. I've already started doing that in a few place and I'll try to do it more as my Swift proficiency increases. My preference is to have classes be in Obj-C or Swift, rather than a mix of the two.

Feel free to delete/ignore code #ifdef code when converting to Swift. If you let me know which classes you plan to work on I'd be happy to provide comments.

**Comment by bryceco** [comment]
Closing since this isn't an issue
