### ISSUE TITLE
UI Button Location Suggestion

### ISSUE THREAD

**Issue by patricks** [bryceco/GoMap#380]
Here is my suggestion for the button locations.  

![image](https://user-images.githubusercontent.com/132167/88832979-ea730d00-d1d1-11ea-97cc-7e788c8c28a2.png)

**Comment by dieterdreist** [comment]
Mine is similar. 
![IMG_8164](https://user-images.githubusercontent.com/581288/88936989-d1c32f80-d283-11ea-9307-53cb1d116bea.PNG)

**Comment by bryceco** [comment]
Those are all good comments and the layout looks pretty. Even though I try to avoid thumb input for ergonomic reasons having + on the left works well for adding nodes quickly.

**Comment by dieterdreist** [comment]
IMHO unless you are holding the phone in the left or want to prevent from accidental pushing the button it is a UI fail. A possible reasoning for the GOOG to do it may be in their logo situated on the left bottom. If you look at Apple they show the click-me-buttons on the left:

![6948896C-6EA1-4983-B925-C49533DDA977](https://user-images.githubusercontent.com/581288/88945719-a09c2c80-d28e-11ea-897e-e1ef24f900c0.png)


the end button is on the right because you should not tap it normally.

**Comment by bryceco** [comment]
I hold the phone with my left hand and use a stylus with my right. Tapping + with either my left thumb (easier if the button is higher) or the stylus is pretty easy, and then I drag nodes with my right. 

If opinion is strongly divided we can have multiple layouts, for left-handed users etc.

**Comment by dieterdreist** [comment]
I’ve been looking around and it seems right-handed people typically hold the phone with their left hand so they can type with their stronger hand, and vice versa

**Comment by daviddahlberg** [comment]
I either hold the phone in my left hand and type with the right index finger, or have it resting on my right little finger while typing with the right thumb. I frequently require (+) and (change map). The lower edge, and esp. lower corners of the screen is a bit unergonomic in both situations: Long ways in left hand; Bottorm left cannot be reached - almost worse: bottom right can just be reached, but makes my fingers hurt in the long run.

The placement of patricks looks about right. Would rise the (+) to a middle-ish position though. Don't care about wind rose, locate me , upload info and settings, because they are more rarely used. So probably move them out of the way to the lower or left edge.

In the beta I noticed, how often I accientally hit (i) and the wind rose while editing. So probably top right is not the best position for buttons either.

**Comment by dieterdreist** [comment]
I like the idea of offering different layouts

**Comment by bryceco** [comment]
Nothing is final yet, but this is the direction I'm leaning toward, with a configuration option to have + and Display be on the right. I'm still very interested in any feedback and comments. 

![Simulator Screen Shot - iPhone 11 - 2020-07-31 at 21 38 57](https://user-images.githubusercontent.com/279734/89094216-5ee6b100-d376-11ea-823c-826c55eed8c1.png)

**Comment by bryceco** [comment]
Also, I'd like input on how the layout will translate to iPad.

**Comment by TheAdventurer64** [comment]
I think the first one is my favorite, as it seems the most professional and organized. The last one looks unprofessional and messy. I’ll try and develop my own and send it here.

**Comment by TheAdventurer64** [comment]
![C7020342-4391-47BB-8A00-D701A9A92BA2](https://user-images.githubusercontent.com/50059322/89094432-8a11d600-d35f-11ea-82bd-f6f942555841.png)

**Comment by bryceco** [comment]
Looks are secondary to utility. I'm trying to put the most commonly used elements at the top where they are easily accessed without strain, while also clustering by function. I also want to physically separate the Display and Settings buttons to reduce confusion about their purpose.

**Comment by TheAdventurer64** [comment]
Why aren’t you going to merge the two features?

**Comment by tordans** [comment]
Hi, I am a bit late to the discussion. 
I wanted to get some experience with my layout suggestion while using it, but did not manage so, yet. Will update once I did.

Btw, making the buttons move around is a great idea, Bryce, which allows us to test out new positions in the wild. Thanks!

# Primary Action accessible with a relaxed thumb.

The main action for me is to add tags, and I would love to have this place in a way that make mapping less "painful" for my fingers. For me, that is on the middle right, where I can easily access it without bending my finger.

It also allows to easily hold the phone while press-holding the "+" to multi-tab in the UI when creating a line with the other hand. This is also the reason, why the left is no ideal IMO, since you need to reach with hour finger and obscure the map for the other hand. How do you use this action, with the button on the left?

Btw, this also shows, that left hand usage is an issue here; but thats for all layouts that dont follow the "button in the bottom middle"-layout.

Undo/redo belong to the "+" IMO, so they are next to it. I at least use them together a lot.

|   |   |
|---|---|
| ![IMG_8856 Kopie](https://user-images.githubusercontent.com/111561/89094821-659e1400-d3c8-11ea-986b-337a176f7fc1.jpg)   | ![IMG_3179 Kopie](https://user-images.githubusercontent.com/111561/89094882-10aecd80-d3c9-11ea-9371-da03bb04bcf0.jpeg)    |


# Other actions

- **Upload** is in the bottom right which is a place that is hidden most of the time by my hand. Which is OK since I only need it at the end of a mapping session or at least seldomly.
- **Settings + Info** should be somewhere out of the way – for example top left; but other places are fine as well, depends on the overall design IMO.
- **Map-Stuff** like Map-Settings, GPS, Compass in the top right, since I need them a again and again, so they need to be easily accessible.

# What about tags/paste/delete

I wonder, what about the other actions that appear?
IMO we need to think about those as well when choosing new button positions because one needs to use on of the buttons nearly always right after using the "+", so they should be very easy to reach.


|   |   |
|---|---|
| ![IMG_8857 Kopie](https://user-images.githubusercontent.com/111561/89094842-97af7600-d3c8-11ea-97c6-1f2a8f58a645.jpg)   |  ![IMG_8858 Kopie](https://user-images.githubusercontent.com/111561/89094864-e9f09700-d3c8-11ea-9a5e-bc64073fbeec.jpg)  |


# Offtopic: Extract part of the map-settings?

I find myself using the map-settings _a lot_ to change the background (hide the image layer or change the image layer).
All other actions in the map-settings are used a lot less frequent by me. 
Would it be possible to extract the image layer selection to a separate icon? An maybe merge the filter-feature in this new Scene (that is the iOS Term for a page, right?) as well?
I dont have a scribble, yet; would you be open to talk about it Bryce? If so, I will extract this to discuss in a separate thread.

**Comment by bryceco** [comment]
Here’s a video of how I adjust position with my right (dominant) hand while pressing + with my left hand which holds the phone:
https://share.icloud.com/photos/0VfcANTw_UdTcpRD9UgHkdtIA

**Comment by bryceco** [comment]
And here's another video using the press-and-hold technique of tracing a building. Again it relies on having the + activated using the non-dominant hand: https://share.icloud.com/photos/080xFnNsxPPYX0uPX0WK7ysaA

**Comment by TheAdventurer64** [comment]
Quick suggestion regarding the new buttons: Are you going to clean up the information button so that it doesn’t look as pixelated?

**Comment by TheAdventurer64** [comment]
Add a in-progress tag to let people know that you are working on this.

**Comment by daviddahlberg** [comment]
> Here’s a video of how I adjust position with my right (dominant) hand while pressing + with my left hand which holds the phone:

I tried your technique and it works quite well when working with two hands. And fact If you add a switch to settings which mirrors the layout, I'd say it works for most situations: Dominant right/left hand, one-handed and two-handed usage.

**Comment by bryceco** [comment]
Another preferred layout posted on Twitter:
![IMG_0401](https://user-images.githubusercontent.com/279734/89442331-268afe00-d6fb-11ea-817f-f1801155d430.jpeg)

**Comment by tordans** [comment]
Quick update from my experience of the last few mapping days:
- I am still getting used to the (any) new layout, so don't feel like I can really say its better or worse. I still click the wrong buttons due to muscle memory.
- I am still looking for a layout that allows one hand usage primarily and two hand only when needed. The current layout is more focused on two hands from the start IMO.
Btw, I could not open the first video (get some weird error about network connection, but can see the second).
- IMO the node related action "+", undo/redo, "tags" etc should be in the same area. Right now they are all over the place. (Left +, right undo, bottom Tags)

My current suggestion: Let's try this for some more time.

**Comment by bryceco** [comment]
Additional feedback on button layout is welcome, but for the upcoming release it is what it is.

**Comment by dieterdreist** [comment]
sent from a phone

> On 23. Sep 2020, at 23:51, bryceco <notifications@github.com> wrote:
> 
> ﻿
> Additional feedback on button layout is welcome, but for the upcoming release it is what it is.
> 


I just wanted to thank you for the mirror buttons option, was quite happy when I discovered it :)
