### ISSUE TITLE
Map-cycle button

### ISSUE THREAD

**Issue by daviddahlberg** [bryceco/GoMap#389]
Picking up the UI improvement theme from issue #380 ...

As I wrote there, I cycle through different underlays a lot Having a look at the suggested layout by @bryceco, you seem to do this too. And @tordans actually voiced basically the same request.

Here is my suggestion. Currently, changing a map requires a lot of clicks; Also favourite underlays are often far apart and not easily locatable on first glance.

So:
* Move map setting as they currently are to Settings menu.
* Change the behaviour of the existing map selection button to cycle through the the layouts which are marked as "favourite" in settings.
* Alternatively: Map selection opens a quick-menu to chose a underlay map and a toggle to enable/disable editor overlay

**Comment by bryceco** [comment]
This is an interesting idea, but I have concerns:
* How is this discoverable? What is the behavior when nothing is favorited (the most common situation)?
* The available imagery depends on your location, so there might be confusion about why something you favorited isn't available where you're currently mapping
* I still like have everything related to map display under Display. It's an intuitive category which gets disrupted once settings get split into different settings buttons.
* Changing the aerial currently requires 3 clicks (plus very likely a scroll action). This changes it to 2 clicks, but is that really enough for a dedicated button on a UI that is already crowded?

**Comment by bryceco** [comment]
I’m thinking about having a long-press on Display settings display the most recent aerials so quick-switch between them. The idea to toggle editing is interesting but I don’t know how often people would use that.

**Comment by bryceco** [comment]
Fixed in 5baffc90856c6fde846832ebd20b3f02567436c1. You can now long-press Display to access recent imagery.

**Comment by tordans** [comment]
@bryceco this is a great idea.

One thing I am missing for this is the ability to also (de)activate the areal images. Most of the time, I have them off to save bandwidth. So my settings look like this:
![IMG_1937](https://user-images.githubusercontent.com/111561/99917250-4f1d1f00-2d0f-11eb-8dbc-bb0a35d26d5b.png)

With this setup, the long-press shows:
![IMG_1938](https://user-images.githubusercontent.com/111561/99917260-622fef00-2d0f-11eb-8dc1-849528dd6cb7.png)

And once I choose a areal image layer in this list, nothing happens, because I first need to activate the areal images in general.

Ideas to improve this:

- Add the choice "Editor with areal", "Areal only", "Editor only" as a second group of choices to the new long-press UI.
_and/or_
- Whenever I select an areal image layer, also switch to "editor with areal"
- Whenever I unselect an areal image layer, also switch to "editor only"

**Comment by bryceco** [comment]
There's no way to create a second group of buttons without a custom action sheet. I tried just putting a marker next to the new options but it's kind of ugly. Any ideas?

![IMG_3698](https://user-images.githubusercontent.com/279734/99925560-76fe8980-2cf3-11eb-8952-92cfffc17561.png)
