### ISSUE TITLE
support disused and abandoned lifecycle tags

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/GoMap#399]
current lifecycle concept suggests to prefix the main key with “disused:” or “abandoned:” rather than adding disused=yes or abandoned=yes tags (actually it is a bit more complicated, because some combinations like landuse=quarry should get the disused=yes qualifiers).
GoMap!! doesn’t currently interpret these prefixes (it stops showing the symbol when you add these). I could imagine modifying the symbol for these, like setting opacity<1 or strike through the symbol, on the display part.
For editing it would be convenient to add the prefix with a wizard (like: tap modifier button once to show a menu where buttons could be something like disused, abandoned, cancel, possibly more), to add the prefix (like disused:amenity=* for disused amenities).

**Comment by bryceco** [comment]
I recently encountered a similar issue with a disused:building that was still a perfectly reasonable building, but no longer occupied. I thought it pretty annoying that it didn't display as a building (which it is) simply because it is currently unoccupied. So, until there's an obvious consensus that it's wrong I'm closing this. As usual I'm following iD for these decisions, so please file your bug reports there :)

**Comment by dieterdreist** [comment]
sent from a phone

> On 20. Aug 2020, at 07:08, bryceco <notifications@github.com> wrote:
> 
> ﻿
> I recently encountered a similar issue with a disused:building that was still a perfectly reasonable building, but no longer occupied. I thought it pretty annoying that it didn't display as a building (which it is) simply because it is currently unoccupied.
> 


yes, I would consider disused:building a tagging error. These lifecycle prefixes are for functions, not for physical objects. For a building, disused=yes would be suitable tagging
