### ISSUE TITLE
Help with updated presets

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#442]
Hey there! Is there any way I can help update GoMap's presets to the latest ones from iD?

**Comment by bryceco** [comment]
Unfortunately this is a manual process. Although copying the presets can be automated it's fairly common for iD to introduce new code that needs to be updated concurrently and can result in app crashes, so testing and updating code is the bottleneck rather than copying the presets.

**Comment by TheAdventurer64** [comment]
Well, could I help?

**Comment by wtimme** [comment]
@bryceco, could you outline the steps that you undertake to update the presets? Maybe someone has an idea how to improve and speed up the process.

**Comment by bryceco** [comment]
Sure, this is a rough outline:
- Update the preset files in src/presets with the equivalent iD files. This is a simple download/copy. 
- Since new presets may have new icons or icon names may have changed we should also update the icons in src/POI-icons:
— Download the icons from the respective sources
— Convert SVG to PDF and rename to have the name prefix expected by the preset database
- We also need the translations for presets (I only use languages that are largely translated)::
— Download preset language files from https://www.transifex.com/openstreetmap/id-editor/presets/
— Convert them from YAML to JSON
— Copy to src/presets/translations 
- Test and add new code to src/Shared/PresetsDatabase.m as needed for schema additions


I have scripts for parts of this but there are lots of manual steps.

**Comment by bryceco** [comment]
You can download Inkscape and use it to convert SVG to PDF (necessary because only iOS 13 and later support SVG): 
- Inkscape.app/Contents/MacOS/inkscape  --export-type=pdf *.svg

To rename files with the proper prefix use:
- for f in `ls *.pdf`; do echo mv $f `echo $f | sed 's/^/maki-/;s/-15//'`; done | bash

where "maki" is replaced with the appropriate prefix (maki,temaki,tnp,fas or poi)

**Comment by bryceco** [comment]
There's a script at src/presets/update-translations that will download translations from transifex and convert them to json

**Comment by wtimme** [comment]
Thanks for the detailed steps!

I've started with the automation by adding a new Fastlane plugin. The first action, [`update_presets`][update-presets-action], allows for an easier update of - you guessed it - the presets. Basically, it is the automated version of the first step.

The next steps would be to automate the download of the icons, for which we need to parse the preset JSON, retrieve the SVG files and feed them to Inkscape. (For a start, refer to the [`update_icons`][update-icons-action] action.)

---

In the end, updating the presets and the corresponding icons could be an automated step before a new release is built. With proper tests in place (cp. Bryce' comment on adding new code to `PresetsDatabase.m`), this could make updating the presets fairly easy and straight-forward.

I'm looking forward to your feedback, ideas and suggestions. Have a nice day, everyone!

[update-presets-action]: https://github.com/wtimme/GoMap/blob/feature/Add-fastlane-plugin/src/iOS/fastlane-plugin-gomap/lib/fastlane/plugin/gomap/actions/update_presets_action.rb
[update-icons-action]: https://github.com/wtimme/GoMap/blob/feature/Add-fastlane-plugin/src/iOS/fastlane-plugin-gomap/lib/fastlane/plugin/gomap/actions/update_icons_action.rb

**Comment by tordans** [comment]
This could change - and improve - the process: https://github.com/openstreetmap/iD/pull/8175

It might also be an opportunity to look into improving the custom tag feature.

**Comment by quincylvania** [comment]
> This could change - and improve - the process: openstreetmap/iD#8175

Yes, we're spinning out the presets to their own repo! One of the goals is to make it easier for non-iD projects like GoMap to use them. Some improvements I'm thinking about that could help:

- Semantic versioning so you can be warned about breaking changes
- Shipping the JSON translation files with the other preset data

It's also easier to extend the functionality if there's something specific you need.

**Comment by quincylvania** [comment]
iD presets now live [in their own repo](https://github.com/openstreetmap/id-tagging-schema). We'll be shipping this a version-controlled npm package separate from iD, which should help avoid unexpected breaking changes.

The preset-only translation files are located [here](https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations) and will be updated with every release. There's a [translations/index.json](https://github.com/openstreetmap/id-tagging-schema/blob/main/dist/translations/index.json) file that lists all the available languages and their completion percentages.

**Comment by bryceco** [comment]
Thanks for the update!

**Comment by bryceco** [comment]
I updated scripts to pull data from the new id-tagging-schema GitHub repo (not npm). Just a few bumps to get everything working, and having the translations already in JSON is great. The only breaking changes besides file names/locations was maxspeed -> roadspeed and the new geometry definition (array instead of comma separated string).

**Comment by quincylvania** [comment]
@bryceco Great! I haven't see your implementation, but I'd avoid relying directly on the `main` branch since we may push breaking changes like the roadspeed thing. For iD we'll be using jsdelivr URLs that specify the maximum major version, like: https://cdn.jsdelivr.net/npm/@openstreetmap/id-tagging-schema@2/dist/presets.min.json.

But if you only update things manually then you have more flexibility.

**Comment by bryceco** [comment]
I plan to update manually for the time being, but maybe once I'm more comfortable with the new system I'll automate it. Also I'm still pulling address_formats.json directly from the iD repo.

**Comment by TheAdventurer64** [comment]
#469
