### ISSUE TITLE
Support Dark Mode for map rendering

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#453]
> As a mapper, I want the map elements such as areas and ways to use darker colors when "Dark Mode" is active, so that mapping at night puts less strain on the eyes.

# Motivation

The app's UI integrates with iOS' Dark Mode quite well already. The main interface, the map, however does not yet.

# Open questions

- Where do the colors currently come from?
- Is there a dark color palette for OSM already exist that we could utilize?
- Are there any refactorings that we should do beforehand?

**Comment by bryceco** [comment]
Colors for ways and areas are in src/Shared/RenderInfo.json. These are meant to be similar to iD colors but maybe not exact. 

Adding dark mode equivalents is probably straightforward (but still a lot of work).

**Comment by tordans** [comment]
@wtimme to me, this sounds like quite a bit of complexity-dept that could potentially slow down further development and increase testing efforts. This is true for all darkmode feature, I guess, but for something like the map its especially true, IMO, due to all the details of design that have to be manually evaluated. 
To look at the complete complexity-picture: Its not only the map style but also other features that put design elements on the map – like the highlighting of unnamed roads or the new filter-feature – that need to be forked for non-dark-mode and dark-mode.

My personal view is: The map looks good to me on dark mode already, so IMO its not worth the additional effort (one time and future (testing, maintaning, future feature)).

---

On a side note, I really liked reading http://blog.imagico.de/the-way-of-the-water/ and those other posts http://blog.imagico.de/tag/map-design/ about all the details that need to be considered when creating a map style. 
And of course also https://www.justinobeirne.com/cartography-comparison (+ the other parts).

**Comment by bryceco** [comment]
https://github.com/bryceco/GoMap/tree/feature/453-dark-mode makes a stab at implementing the color change in code, automatically lightening all colors when in dark mode:
![image](https://user-images.githubusercontent.com/279734/94328238-a7c97900-ff65-11ea-98f9-d62e9b8b41a6.png)

**Comment by wtimme** [comment]
Wow, that's a great start!

**Comment by bryceco** [comment]
Fixed in 984e6792449105a59db50f59e04e70bba6085788
