### ISSUE TITLE
Info Buttons on GoMap are Too Small

### ISSUE THREAD

**Issue by TheAdventurer64** [bryceco/GoMap#487]
![image](https://user-images.githubusercontent.com/50059322/104245167-db8eb880-5407-11eb-8548-2f8d07bdd3aa.png)
The problem with the info buttons in the image above is that the style is inconsistent with the other information buttons, along with buttons such as the Height and the Link button.

**Comment by bryceco** [comment]
That's intentional since horizontal space is already somewhat cramped, those buttons consume real estate on every row, and I consider those to be secondary buttons. The tag-specific buttons are less frequently displayed and are more directly tied to tagging so they are full sized. At least that's how I see it. I'm happy to hear more opinions from users what they'd prefer.

**Comment by TheAdventurer64** [comment]
Even so, it would nice to see the style of the buttons reverted to the previous style.

**Comment by bryceco** [comment]
Nobody else is giving an opinion, and I happen to like the smaller/unobtrusive buttons. Sorry.
