### ISSUE TITLE
IPadOS mouse/trackpad support

### ISSUE THREAD

**Issue by endim8** [bryceco/GoMap#553]
Using a mouse, the scroll wheel doesn't zoom. The control scheme for creating a new object/placing nodes should also be similar to iD when using a mouse/trackpad

Zooming by using the expand gesture on the magic keyboard trackpad is also way too fast

**Comment by bryceco** [comment]
> Using a mouse, the scroll wheel doesn't zoom.

Fixed in 9bdc3901510e5ff144f8906e3fd8f5609389183b, so look for it in the next release.

> The control scheme for creating a new object/placing nodes should also be similar to iD when using a mouse/trackpad

iD's approach is too different from what we already have. On Mac Catalyst I'm using an approach where right-click is used to create nodes and it works pretty well, but unfortunately right-click doesn't behave sanely on iPad (there's no way to differentiate a right-click vs. a long-press with finger/left-mouse). I'm hoping that in the future there will be a workaround for this.

> Zooming by using the expand gesture on the magic keyboard trackpad is also way too fast

I'll look into it, but I suspect that it won't be possible to support different zoom speeds for different devices, because the API doesn't typically identify where the command originates.

**Comment by endim8** [comment]
> Fixed in [9bdc390](https://github.com/bryceco/GoMap/commit/9bdc3901510e5ff144f8906e3fd8f5609389183b), so look for it in the next release.

Wow, that was fast! Thank you so much 😄


> iD's approach is too different from what we already have. On Mac Catalyst I'm using an approach where right-click is used to create nodes and it works pretty well, but unfortunately right-click doesn't behave sanely on iPad (there's no way to differentiate a right-click vs. a long-press with finger/left-mouse). I'm hoping that in the future there will be a workaround for this.

No worries, admittedly it would be a pretty major rework 😅


> I'll look into it, but I suspect that it won't be possible to support different zoom speeds for different devices, because the API doesn't typically identify where the command originates.

No worries, mapping with a trackpad is probably a bit impractical anyway haha

**Comment by bryceco** [comment]
I got right-click working so things should be pretty good on iPad now.

**Comment by endim8** [comment]
Awesome, thank you :D
