### ISSUE TITLE
MINOR: URL parser complains about 'Invalid URL', but URL is valid

### ISSUE THREAD

**Issue by habi** [bryceco/GoMap#597]
[/relation/9803160](https://www.openstreetmap.org/relation/9803160/) has a weird, but [valid URL](https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Installation_Magisches_Tor_(Walter_V%C3%B6geli_%E2%81%84_Urs_von_Arx_1987-1992)_02.jpg/800px-Installation_Magisches_Tor_(Walter_V%C3%B6geli_%E2%81%84_Urs_von_Arx_1987-1992)_02.jpg) in its `image` tag.

Go Map!! (Version 3.1.4 (3104)) does not like the URL and complains about it not being valid when clicking on the 'link' button.

![IMG_9111](https://user-images.githubusercontent.com/1651235/167584994-03aa8c2b-de39-4e5f-9a8c-122090cc6853.png)

**Comment by bryceco** [comment]
Wow that’s quite a coincidence because I just fixed an issue with an invalid image tag that was reported privately. It looks like your issue is the same: a URL with a non-ASCII character that needs to be escaped when sending it to the server (the ö in Vögeli). There’s a discussion on slack if you care: https://osmus.slack.com/archives/C2VJAJCS0/p1651792952860889. 

The next release should have a fix.
