### ISSUE TITLE
Feature request: “Pinpoint Zoom” when moving object(s)

### ISSUE THREAD

**Issue by andrewjbates** [bryceco/GoMap#603]
In the Microsoft Office Lens application, the crop tool shows a zoomed-in view of the corner that’s being adjusted. This would be excellent for nodes and may also be useful for moving ways. Example attached: 

![16694688-128C-4C77-8E1C-FB86481C5222](https://user-images.githubusercontent.com/11239183/172069572-ae36d4f9-de72-467b-85f2-845c590d23ad.jpeg)

**Comment by andrewjbates** [comment]
The magnifier only appears when touching the screen to move the corner.

I will work on getting a video for you.

Lens is also free in the App Store if you want to try it yourself.

**Comment by bryceco** [comment]
I just downloaded it so no need for a video. It looks like they implemented this in order to get around the problem of your finger covering the object you're dragging, which isn't an issue for us since we drag with the label. But it seems like something that would be helpful for Vespucci!

Nevertheless I do think it's worth prototyping to see if people like it when tracing buildings, etc.

**Comment by bryceco** [comment]
I've started looking into this. Initially added a magnification window that just mirrored what was on the screen, but as you can see the UI elements block all the interesting bits: 
![image](https://user-images.githubusercontent.com/279734/208326331-447df08e-b3b9-4acc-88d9-fef42e7a9c36.png)

Next try was to display only aerial imagery which I think works better, even though you lose some of the context:
![image](https://user-images.githubusercontent.com/279734/208326459-0406e937-8af9-43bd-9616-0172eb3d666b.png)

Either way the new window only appears when the pushpin is visible.

I'll include it in the next beta so people can give feedback.

**Comment by tordans** [comment]
First impression on this prototype from the recent testflight:

Fist my goal: I want to build a great building shape in OSM. Which for mean is a combination of "shape fits the areal image" but also "shape has a nice (square) form".

- The magnified view does not really help me with that:
  - The images in Berlin are not precise enough for privacy reasons; zooming in in the editor is enough for my workflow. 
  - I have to decide if I want to put the pin in the inner or outer (or inner) building "shadow" (in your example it's in the inner part); the zoomed in view makes that harder, since its harder to see the context of how other pins where placed.
  - The added precision lets me fiddle with details which lead to less square buildings; so I will remove the precious by squaring afterwards…
- The logic when the magnifier is hidden again is not great, yet. It should only be visible while I drag a node, IMO. Not when selecting an object.

**Comment by bryceco** [comment]
Your first points are well taken. I'm going to have to do more mapping before deciding how much I like it.

I agree with your second point, and changed it to only appear when creating a new node, or dragging a node. Deciding when to hide it again is more complicated, so I'm leaving that as it is for now.

**Comment by habi** [comment]
I like the Zoom a lot, also because the Swiss aerial imagery from swisstopo is rather high resolution.
How it moves out of the way and is toggleable in TestFlight build 3.2.1 is - in my opinion - a cool feature.
I vote for ‚stay‘ ;)
