### ISSUE TITLE
Request update and sorting of Fuel Types selection dialog

### ISSUE THREAD

**Issue by kevinp2** [bryceco/GoMap#620]
1) I have added new Octane levels commonly found in the western US to the list of fuel types maintained in https://wiki.openstreetmap.org/wiki/Template:Fuel_types  I understand that GoMap maintains this manually (I could be wrong).  If so, please update the list of Fuel Types in Go Map.

2)  Currently, the list of Fuel Types is presented in an unsorted and seemingly random order.  It would be great if they could be sorted as follows:
By the friendly name, if available, e.g. Octane 85
If not available, by the tag, e.g. fuel:octane_85

This would make it very easy to tag a gas station with the list of available fuels.

Pics are attached.

![image](https://user-images.githubusercontent.com/609677/196514239-8fcffd0d-132b-47d9-bc9d-afa4301bb88a.png)

![image](https://user-images.githubusercontent.com/609677/196514273-a2833efb-04b3-406d-a5a3-96c4284ed204.png)

**Comment by bryceco** [comment]
Go Map!! presets are based on the templates (and translations) that iD uses, so that information would have to be incorporated at https://github.com/openstreetmap/id-tagging-schema

The list of fuel types is based on the returned order by Taginfo, which corresponds to number of uses highest to lowest:
https://taginfo.openstreetmap.org/search?q=fuel%3A
This is the same order that iD presents them.

Unfortunately there is no friendly name available from Taginfo, but they could be sorted by tag value.

**Comment by bryceco** [comment]
I just noticed that these were also added to iD tagging schema a few days ago, and the friendly names are also there and listed as a sorted array, so that should take care of everything!

**Comment by kevinp2** [comment]
Thanks for the update.  I noticed that a few octane levels were missing, so I submitted a request to add them:

https://github.com/openstreetmap/id-tagging-schema/issues/621

**Comment by bryceco** [comment]
This is now fixed with the newest presets release.
