### ISSUE TITLE
Feature request: free-form quest creation 

### ISSUE THREAD

**Issue by tohaklim** [bryceco/GoMap#628]
Hi Bryce, many thanks and really well done on the quests release!
I haven’t noticed any issues or performance impact from having even a heavily saturated area render the quest icons. 
Really nice to have the ability to build custom ones, but any reason why you limited the builder (and the json parser from what I can tell) to only accept a set list of values? is this linked to iD presets?

Eg I was going to add a quest where entrance=staircase has no ref or addr:flats, to fill these in.

**Comment by bryceco** [comment]
Yes, the quest builder is exactly tied to the iD presets database. Instead of manually building a filter function I'm using the presets database to generate it automatically. 

I'm open to having a more advanced quest builder with more options (or maybe just supporting a more complex JSON file), but I'd like to have more feedback on what people need (so this feedback is great!). I previously wrote a parser that can consume the types of filters that the StreetComplete code uses, and that's one extreme, but I'd like to see if we can get by with less. Ideally we don't ask users to learn pseudocode to write a quest. A lot of the complex features in StreetComplete still need to have additional support with native code, in which case supporting a sophisticated builder language still isn't enough to allow users to do everything they want.

BTW, my initial thought was to have the user select a preset field (like "payment_multi" which supports setting lots of payment:* values at once) but that turned out to be too complicated and too fragile. The fallback is to select the tag key to be set, but there's some loss of generality.

**Comment by tohaklim** [comment]
Ah, that makes a lot of sense then. 
What StreetComplete is doing seems overly complicated for this use case, and has its limitations. 

Judging by how you say supporting a multi field was too fragile (I haven’t looked at the code), supporting multiple tags to be added (eg both ref and addr:flats) may also not be feasible.

**Comment by bryceco** [comment]
I spent some time thinking about your particular quest and a more advanced quest builder. This would be second way to define quests. (The underlying code is very general, it's only the quest builder page that creates limitations by simplifying things.)

There would be a quest filter that looks like: 
- entrance=stairs: include
- addr:flats=*: exclude
- ref=*: exclude

Then for the key to set we'd have: 
- ref,addr:flats

and the quest solver would bring up a page like Common Tags but that had only those two keys' presets. At that point you could choose to set one or both values.

**Comment by tohaklim** [comment]
That seems like what I imagined.
If the quest solver can bring up a version of common tags, even without the predefined list of values (I have it for this scenario, but it’s a custom preset), would improve the entry process even more.

**Comment by tohaklim** [comment]
Amazed how you managed to push the new quest builder so quickly! It’s much more flexible. 
But, give a man a fish…
I’ve tried adding multiple values to be filled in a quest with a separator (;), and that is obviously not supported. 
So I thought I could just eg use the quest to add a ref, and then switch to the tag editor. 

That’s where I noticed this action pattern doesn’t quite work:
- open the quest window,
- Add data for the quest (ref in this case)
- Switch to the full tag editor via the button in the quest window
- Data input in the quest window (ref) is not retained. 

Please let me know if I should move this to a separate issue, or if you prefer to get my ramblings via the TestFlight emails

**Comment by bryceco** [comment]
Right, I don't actually save the tags unless you press Save. I can add a pop-up that asks whether to save or discard changes if you make an edit and then open the full editor.

**Comment by tohaklim** [comment]
That would definitely help with my workflow, and shouldn’t impede anyone just using the quest window and saving

**Comment by bryceco** [comment]
Just an FYI, I previously said you'd build the filter like:
> * entrance=stairs: include
> * addr:flats=*: exclude
> * ref=*: exclude

but that is no longer true. With aecf8f6cbd68bbe8551272fd36a1d73c75e0f3f5 it will need to be:
* entrance=stairs: include
* addr:flats=: include
* ref=: include

The different conditions are ANDed together when the tag keys are different, and ORed together when they're the same.

**Comment by tohaklim** [comment]
Thanks, I figured it would be along those lines. 
given how easy it is to build quests, I can just create new ones to catch edge cases like 
ref=(value) but addr:flats=(no value)

**Comment by tohaklim** [comment]
The latest version of the advanced builder is great! Incredibly flexible, and pulls in the custom preset values. Also nice to see you’ve added the Save changes pop up, thanks!

One thing I’ve noticed just now (but which was there to begin with) is that if a preset (custom or not) exists for a tag, only the values from the preset are shown in the quest - ie no blank field to be filled out, like what is shown on the Common Tags for suck keys. 
I think working around this (by adding more values to the custom preset, or just opening the tag editor) will be easier than building support for a wildcard value - you did mention supporting preset multi fields was tricky

**Comment by bryceco** [comment]
Closing this. Please create new issues for additional comments. Thanks!
