### ISSUE TITLE
Quests: Allow to filter for multiple values

### ISSUE THREAD

**Issue by tordans** [bryceco/GoMap#644]
I am trying to create a quest that should only apply, if `access!=private || destination`.

---

I tried this …
![D1BFE873-BFD2-4A1D-93D9-18A5573129FB_1_105_c](https://user-images.githubusercontent.com/111561/222956129-64af85e8-b361-4bf4-b67f-fc8a1d3394ff.jpeg)

… but the quest are applied regardless ATM
![3884783C-9AE4-460A-9800-F18A1948CB92_1_102_o](https://user-images.githubusercontent.com/111561/222956078-31bd0602-8c01-4fc6-b9e7-8b219c5857af.jpeg)

**Comment by bryceco** [comment]
Thanks for reporting this. The issue here is that the exclude filter applies only when all exclude conditions match, so it excludes when "highway=street_lamp && access=private". I'll change it to be an OR condition instead which should simplify things, but at the cost of being inconsistent with include which remains AND.
