### ISSUE TITLE
In map editor view, give user the option to show names of map features in locale language

### ISSUE THREAD

**Issue by sanketgarade** [bryceco/GoMap#657]
Currently the name shown for any element is the one stored in the `name` tag. Instead, can it be changed to show the one stored in the `name:xx` tag where `xx` is the locale (I.e. the language set in GoMap) ?

(Similar to what you experience in JOSM).

**Comment by bryceco** [comment]
Thanks for the translation work you've been doing!

I agree that there should be better support for name:xx. One way you can handle it on your own is to add a custom preset which will always display the name:xx field on all objects. But if it's built into the app then I think it needs to show both name and name:xx, rather than name:xx only.

I'd like to hear some opinions on this.

**Comment by sanketgarade** [comment]
> Thanks for the translation work you've been doing!

Welcome! And nice of you to notice it :)

Sorry if I created a confusion. When I said "editor" I meant the editor view of the map, not the tags editor.

In the tags editor, of course both the `name` and the `name:xx` should be supported. But in the map editor view currently the POIs, roads, buildings etc all display the content of the `name` tag, which I want to be able to change to `name:xx` tag.

Reason for this is, in India the community convention is to use English in the `name` tag instead of the local languages ([because there are a lot of them](https://en.wikipedia.org/wiki/Multilingualism_in_India)). But for those who are more comfortable to see local language name (as saved in `name:xx`) instead of English name, for them this will help edit the map in a better/faster way.


BTW, 
> One way you can handle it on your own is to add a custom preset which will always display the name:xx field on all objects

Thanks for this! I didn't know about this, I've enabled it right away. Makes adding `name:xx` much faster now :)

**Comment by bryceco** [comment]
Okay, I considered the possibility you were talking about the regular map view 😉. 

Generally I like to follow the lead of what the other main editors (iD, JOSM) do. It looks like iD does as you say (and didn't check JOSM) so I think this is pretty reasonable change.

**Comment by euf** [comment]
Would you possibly consider adding a user preference for that? Switching from displaying `name` to `name:xx` by default may complicate things in some cases. I love to edit OSM while traveling, and in the India example things would get harder for me, because as a tourist I don't speak local languages, and my own (or system, or preset) language may also be different from English.

**Comment by bryceco** [comment]
> and my own (or system, or preset) language may also be different from English.

If your own language is not the same as the local language then it probably won't have a name:xx value, and we'd fall back to showing the name=* value.

However, at this point I'm leaning towards showing both name and name:xx, rather than having people set a preference. I'll release a beta with that change next week.

**Comment by euf** [comment]
Okay, right now I'm visiting a country whose language I don't speak. After using Go Map for a couple of days I realized that the best experience (for me) would be showing `name:en` when available and `name` otherwise with some kind of marker (thinking of a colored dot maybe?) in a label to distinguish between them. Showing both would clutter the map in my opinion.

**Comment by sanketgarade** [comment]
Screenshots from the beta released today. The road still shows the `name` tag value instead of the `name:mr` as it's display name on the map (in editor view). My app language (from iOS settings) is set to Marathi (`mr`). 

![image](https://github.com/bryceco/GoMap/assets/74632379/df0a45c0-bbac-4b62-bac1-abcc0bbefbb9)

![image](https://github.com/bryceco/GoMap/assets/74632379/870a607f-31c5-4094-bcba-90fd208170e0)

**Comment by bryceco** [comment]
I see. That's happening because presets haven't been translated into Marathi yet, so it's treated as an unsupported language and gets ignored. I'll fix it to not do that!

**Comment by bryceco** [comment]
Fixed in 9480935737f0f52dab4f0a6285d78a9d913d6dc9
