### ISSUE TITLE
I have never wanted to move an entire Way

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#704]
I've been using this app for a few weeks now and I have not once wanted to move a Way, but I've done it accidentally about a dozen times. Can you just remove the ability to do that? Or at least add a setting. If I want to move a way I'll move each point. The amount of time I'll spend on that will cancel out all the times I accidentally moved a way and then had to undo stuff and the constant double checking of whether or not I have a point or a way selected.

**Comment by dieterdreist** [comment]
I somehow agree that (intentionally) moving ways is uncommon for mobile edits, although there are some usecases (e.g. move buildings). Selecting ways is common though (tag edits), so even if moving is made more difficult, selection of ways and having to distinguish between a node and a way selection is essential. 

Maybe there could be a (1) switch on the main ui to prefer (or not) nodes over ways and ways over relations in the selection (which one is selected on tap and which requires a longer press). I think I would prefer to select ways over relations on tap (but the current flow has its advantage: it is pointing the editor to the fact that the way is part of a relation).

**Comment by bryceco** [comment]
I agree that moving ways is rare, and occasionally causes problems, which is why there's the prompt to ensure you want to do it. But there are some situations where it's necessary and useful. 

I'm fundamentally against having a switch to control how basic UI works. Currently you drill down to the item you want: Select relation (if present), then select way in relation, then select node in way (a long press isn't necessary). 

I'm closing this until more people complain about the current behavior.

**Comment by mvl22** [comment]
This remains an issue which I too run into very commonly.

This is all to easy to cause incorrect data to be uploaded, if the move is not spotted.

At present the UI provides a highly-available control (the crosshairs) for something that is rarely needed, and then has an Undo/Confirm dialog, clearly recognising this as a likely problem.

I agree that having a setting to toggle this would not be a good solution.

To me the obvious optimal approach is for "Move Way" to be an available option in the "More..." list when clicking on the Way. It is an equivalent kind of operation to those. When selected, this would close the menu and provide the handle, with the Way remaining selected.

**Comment by verhovsky** [comment]
Another gesture could be that you have to press and hold before you can move a way

**Comment by mvl22** [comment]
I don't think that would be particularly discoverable, and it would almost certainly lead still to accidental moves by someone holding a Way a bit too long.

**Comment by bryceco** [comment]
> Another gesture could be that you have to press and hold before you can move a way

Long press is already used for selecting one of several objects, so that isn't a good candidate.

> To me the obvious optimal approach is for "Move Way" to be an available option in the "More..." list when clicking on the Way. It is an equivalent kind of operation to those. When selected, this would close the menu and provide the handle, with the Way remaining selected.

I like this idea in general. But: the handle is already displayed when the user clicks More..., and then clicking Move would take them back to where they were without any indication that a hidden flag now allowed them to drag the handle. There would need to be some visual indicator like the Rotate action. 

Also:
* Changing the behavior might confuse people accustomed to the existing behavior. 
* The one place where moving ways easily is useful is when using Duplicate to make a bunch of copies of an object. This makes that path more difficult.
* We could change Rotate to Rotate/Move and handle everything there.

**Comment by mvl22** [comment]
> Changing the behavior might confuse people accustomed to the existing behavior.

I think people will adjust. UIs change over time. There is a clear problem here IMO which needs to take priority over existing muscle memory.

> The one place where moving ways easily is useful is when using Duplicate to make a bunch of copies of an object. This makes that path more difficult.

I agree that Duplicate should immediately put the Way in draggable mode.

What I'm suggesting is that the handle isn't present in the default state of a Way for which no other action like Duplicate has just been applied. I think the handle should only appear in response to a specific action such as enabling it from the menu or having it auto-enabled having chosen to Duplicate.
