### ISSUE TITLE
Use camera for better location tracking

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#710]
https://developer.apple.com/documentation/arkit/arkit_in_ios/configuration_objects/understanding_world_tracking

Apple's ARKit needs precise and relatively high-refresh algorithms for tracking the phone's position in 3D space using the camera and I think they make that stuff (somewhat) available as an API. It would be cool if you could use my phone's camera for increasing the precision of GPS because whenever I walk a trail twice there's a big difference between both tracks. Mapping twists in trails precisely is impossible.

**Comment by bryceco** [comment]
This might give some improvement, but I don't see it overcoming the downsides:
* You'd have to be holding the phone where it can see the ground/trail the entire time, which is unrealistic.
* The battery drain would probably be quite significant, since you'd be running the camera continuously during your hike. And GPS already causes a lot of drain.

Interesting idea, but not worth it IMO.
