### ISSUE TITLE
Moving a Node in a Way that has a lot of Nodes is laggy

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#711]
To reproduce, find a way with a lot of points, like a wood, select one of the points and move it around. My FPS can go down to what feels like around 5 FPS (on an iPhone 15 Pro), which makes editing those kinds of Ways not fun.

**Comment by bryceco** [comment]
This was pretty interesting to track down. The problem was that when dragging a node we are hit-testing it against all the other nodes on-screen in order to do the merge-nodes animation. But we don't allow merging to a node that belongs to the same way, so the nodes in the way are added to an ignore list, telling us not to hit-test them. When the way has 800 nodes then suddenly the ignore-list test is pretty expensive, but that wasn't the actual problem. The problem is that we override isEqual() for nodes/ways/relations, and isEqual() requires a dynamic cast, and that cast was the expensive part. Since this is a special case where the special isEqual() semantics will never come into play the fix was to change
   `ignoreList.contains(node})`
to 
   `ignoreList.contains(where: { $0 === node })`
