### ISSUE TITLE
White flashes when zooming

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#720]
When I zoom out or in on the map, I can see that Go Map!! clears imagery from the previous zoom level before replacing it with imagery from the new zoom level. The effect is that there are constant rapid bright white flashes lasting a couple frames.

At the very least please make the background color of the map a darker, less harsh color (either pure black or the dark blue of the ocean or something), and ideally get the loading of imagery frame-perfect so that previous zoom imagery is removed and replaced only when the next image can be shown on the next frame only.

It makes sense that zooming out you would have this problem at the edges of the screen where you don't have any imagery at all, though you could mitigate this by having a blurry maximum zoomed out picture of the earth loaded at all times so you can always approximately get the correct color of a tile when zooming out especially on the ocean, but on zooming in this should definitely never happen.

**Comment by bryceco** [comment]
The flashing occurred because layers were provided new content images, but those additions didn't take place immediately (probably because they were animated).
I don't understand why a CATransaction is needed because we are already disabling actions for contents, onOrderIn, etc. so there should not have been any default animation applied.
