### ISSUE TITLE
Copy iD's theme

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#730]
I like iD editor's theme and it would be nice if the OSM editors I use had a consistent theme so I didn't have to learn more than one.

**Comment by bryceco** [comment]
If you're referring to the color palette used for roads, etc. then these are defined in RenderInfo.json. Feel free to update and submit a PR. Some of the other styling, like tunnels/bridges is done in code, but I'm not against changing it. Note that we don't use dashed lines anywhere because of performance impact.

**Comment by bryceco** [comment]
I'm not totally happy with the result of this. I was out mapping a couple days ago and certain lines are very difficult to see:
* trying to see the gray line for a parking lot on top of aerial imagery containing a gray asphalt parking lot is super difficult.
* power lines are also very difficult to see

Part of the problem is that these objects don't have casings. In iD the parking lot has the gray gradient next to it that makes it more obvious. Also the power-line line is thicker than what we show.

**Comment by verhovsky** [comment]
By grey gradient you mean that it's not a complete filled in grey, that the fill stops after 60px?

**Comment by bryceco** [comment]
Yes. I don't think it's possible without doing a bunch of math on the geometry.

**Comment by verhovsky** [comment]
you could also try adding a faint shadow instead.

**Comment by bryceco** [comment]
I considered that, but I figured the performance impact for a shadow would be higher, and not much better appearance. But maybe I'm wrong.

**Comment by tordans** [comment]
I am also testing the new theme and have a couple of places that are not yet ideal in Berlin. I will try to document them more properly, but a quick list is…
- some outlines lines are white, some are black and I did not figure out yet when/why. I think it might have to do with the implicit "what is an area" concept that iD has; for example `area:highway` is an area in iD
- building passages of footways and service ways have a tunnel-like style in iD, which I am missing
- `building:part` are super tricky in iD and in the new theme even more so. They have a white line and make some buildings white-lined now
- This is a good area to check https://www.openstreetmap.org/#map=17/52.47919/13.43875 because it has a _lot_ of detailed objects and taggings

And I agree, the casings style from iD is one of the biggest missing factors. But maybe we can also introduce a gesture that toggels the wireframe vs. fill style so it becomes easer to see the data, then see the source data and back. Are there any gestures that are not part of the iOS gesture level that could be used, like swiping in from the top right corner into the screen?

**Comment by bryceco** [comment]
@tordans The line styles and casings are translated from the iD source via a script, so in general they should be identical. If you can name specific way IDs that are rendered wrong it would be super helpful so we can see where things are going wrong. It's true that we're ignoring the whole concept of area at the level where colors are chosen, so that could be part of it. 

I personally think the gigantic casings in iD are pretty ugly so I'm happy to leave them behind, though I see the advantage of not filling areas.

**Comment by tordans** [comment]
> If you can name specific way IDs that are rendered wrong it would be super helpful so we can see where things are going wrong.

### Barriers

https://www.openstreetmap.org/way/549291669
<img width="384" alt="Bildschirmfoto 2024-04-30 um 06 35 23" src="https://github.com/bryceco/GoMap/assets/111561/e6a6b34e-d258-4d71-ba5a-7d8a68e31aee"> <img width="315" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/ccf29b2b-c004-4784-821b-e5b91b61f4c1">



### Barrier Curb

https://www.openstreetmap.org/way/1267121761

<img width="300" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/78148461-7b7a-45b8-8e8b-a78ed74d9a6d"> <img width="343" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/dd5339b9-8a28-4e6b-9196-ae4b27a97560">

### Areas

- Area highway https://www.openstreetmap.org/way/1184051602, same screenshots as barrier curb
- Area razed building https://www.openstreetmap.org/way/334062948
  - <img width="262" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/45594989-4b69-4a25-a799-0d50a0efbb40"> <img width="319" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/6929c45d-7bc5-455e-96ad-d5b0e6c7f01b">

### Footway + Footway Building Passage

- Footway https://www.openstreetmap.org/way/585098106
- Building passage https://www.openstreetmap.org/way/585098107

<img width="290" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/29c30838-6fe8-457c-b276-465f5e89bc40"> <img width="403" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/a51fb853-fa63-49b1-83ce-8a90a81ebef5">

### `building:part`

Example https://www.openstreetmap.org/way/560517989

<img width="370" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/88c5371f-84d6-4b0d-a078-c593d7fe5e7c"> <img width="298" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/032a09b1-c790-4c38-bfde-04c528d97b6b">

### All kind of playground line/way

https://www.openstreetmap.org/way/311072326
https://www.openstreetmap.org/way/60443941

<img width="294" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/df85f21e-bfc9-4401-8127-04d722d80b28"> <img width="416" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/e19b3cc1-17e4-4c84-99fb-cbaf7819400e">

### building with black outline

https://www.openstreetmap.org/way/908199103
<img width="148" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/bdf269d7-9d8f-4c3e-8329-88ea3be9e9d7"> <img width="255" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/08198d7a-3248-458c-8bf9-36017e5530e6">



### Missing icon in area

Not sure if this is important, but it is helpfull…
https://www.openstreetmap.org/way/930016301

<img width="272" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/6411f0b4-6d5c-4494-9cbd-f65046e4c31a"> <img width="300" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/fbeffbfc-5d66-44fe-9867-f467b5d3d12c">

### Embarkment

https://www.openstreetmap.org/way/1156140193
<img width="313" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/2ae7c274-b4cb-4571-bc7c-cedec6cc202a"> <img width="302" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/0e3d7f23-417d-4338-a0da-d1ff8be85b30">

### Parking

https://www.openstreetmap.org/way/888505080
Lines are softer(?)

<img width="370" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/a25bbf25-2ceb-45e0-81ac-c1e191f7b6e7"> <img width="328" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/1fa72a73-8d55-43f9-898c-0405d7e70d84">

### Look of path like ways

The dashed lines in iD for Footway, Sidewalk, all the Crossing styles look noticable different in iD. They are thicker and the dash is different. 
I think it is harder now than before to distinguish a bike path from a sidewalk

This area has a few different stiles in one place https://www.openstreetmap.org/way/1000299492

<img width="377" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/694499b4-69c1-4939-bd52-7ced24fb6116"> <img width="481" alt="image" src="https://github.com/bryceco/GoMap/assets/111561/b0c85bd6-2318-4ed7-b098-3fe828d850e6">

**Comment by bryceco** [comment]
Wow, very nice! This is your department Boris @verhovsky ! 😅

**Comment by verhovsky** [comment]
Amazing comment, thank you. I'll look into this on Saturday probably, I don't have my laptop with me right now.

**Comment by bryceco** [comment]
FYI over in Rapid there is a work in progress revamping how styles are done. It may or may not be easier to use that as a basis for the translation:

https://github.com/facebook/Rapid/pull/1384

**Comment by tordans** [comment]
FYI: The way the styles are set up in Rapid is a complete refactor of the iD setup (same styles, different software). That happened a whole back when the new Pixi based map was build. The current PRs (like the color blind PR you linked) build on top of this new foundation.

**Comment by bryceco** [comment]
Good to know! I didn't look into it deeply, I just saw that it was moving more toward a JSON representation.

**Comment by verhovsky** [comment]
https://github.com/bryceco/GoMap/blob/cd7664ee2bc7008d6c8e3c421c658cf73f03645a/src/Shared/EditorLayer/iD/Theme.swift#L34

is wrong. `barrier` is not a primary tag, things can be styled in the CSS without being a primary.

**Comment by bryceco** [comment]
The specific situation I'm trying to handle is when a node doesn't match any feature, but still contains an address tag like "addr:housenumber"="155". This is frequent when importing address information from government sources.
In that situation we return nil and detect that it's an address separately, and can style it appropriately.

**Comment by bryceco** [comment]
f6fe5e961fb2b3a096e62a3936cf20a552cee965 removes that offending line and cleans up some related RenderInfo stuff that isn't needed now that every object gets its own non-shared copy of a RenderInfo.

**Comment by verhovsky** [comment]
barrier curbs (line formed out of grey circles) are still un-styled.

Also there are ways that should have arrows pointing out of the line, for example for [cliffs](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff) "the direction of the way should be so that the top of the cliff is on the left side of the way direction and the bottom on the right side" and when you draw one in iD it draws arrows showing the direction of the cliff using this convention instead of drawing arrows in the direction of the way. [Example](https://www.openstreetmap.org/way/1121962942):

<img width="393" alt="Screenshot 2024-08-27 at 16 56 22" src="https://github.com/user-attachments/assets/9d6ed108-5b9d-4e26-8283-7f2ff40e7b6e">
