### ISSUE TITLE
Custom data overlay

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#731]
iD lets you upload a custom data set which it visualizes in bright pink

<img width="316" alt="Screenshot 2024-03-24 at 23 34 57" src="https://github.com/bryceco/GoMap/assets/5687998/d7d63b98-f4f7-45f4-9d68-9025a8b16efd">

I use this with a government data set of property lines. I would like to be able to set a locally downloaded .geojson file and have it always visualised. A way to toggle showing it would be useful as well. You could also allow snapping points to points in the data.

**Comment by tordans** [comment]
@verhovsky JFYI GoMap can display local GPX tracks since a few month ago. I started experimenting with encoding my custom data in GPX format to get it to show up in GoMap. That kind of worked but I never got around to finish my tests. — But if you know how to code some transformation, that might be a workaround for now…

**Comment by bryceco** [comment]
@tordans idea is a great workaround (though importing GPX tracks has been supported for years, not just a few months 😉). 

Adding first-class support for custom data overlays is low priority, since that's probably more appropriate for a desktop editor. I'd prefer not to add clutter for features that aren't directly applicable to the mobile experience.

**Comment by verhovsky** [comment]
when I am surveying it would be helpful to have the property lines because it would let me see what's private and public land. Instead I have to look at which areas I can and can't go on the desktop ahead of time and remember it or look on a government's website which isn't as nice and doesn't let me preload the data.

**Comment by bryceco** [comment]
What is your source for the property lines and what are the format?

**Comment by verhovsky** [comment]
It's a shapefile. But GeoJSON would be good too (or both, iD supports 4 file types for custom data), there's a command line tool to convert them. I also edit it in JOSM to reduce the amount of data to just my area

https://www.rdn.bc.ca/sites/default/files/inline-files/Parcels_205.zip

**Comment by tordans** [comment]
Just a quick note on a possible workaround we used for a while: You can use QGIS to set up multiple layer of data. Then export that as ZXY Tiles and put them on a simple FTP Webspace. And use those tiles as a custom map background in GoMap. — I cannot find the tiles URL anymore right now, but it it was based on https://strassenraumkarte.osm-berlin.org/?map=micromap#18/52.47347/13.44224

**Comment by tordans** [comment]
More on the feature part of this: I would be great to be able to show 1 or more custom geojson files in GoMap and have them stored on a shared folder so I can update them from my Mac. The GPX Workaround only works well for points and not any area data and its also hard to get the data processed right.
We have quite a bit of open data that I would like to use while on the go but don't because it's just too many steps ATM.

**Comment by bryceco** [comment]
dea8615202f546e4315e7a7408126a087f64d121 is a first step towards this.

**Comment by bryceco** [comment]
I added rudimentary support for this: 
* You can now share a .geojson file to the app and it will display the contents.
* There is no UI whatsoever, so you cannot hide/unhide the layer, add/delete geojsons, etc. All of that is future work.
* If you want to handle other file types (shapefile or whatever) it should be pretty easy to duplicate the code for loadGeoJSON()

**Comment by bryceco** [comment]
9e42b76e4631630415f742310d949b3bbe708df4 adds first-class support for this.
