### ISSUE TITLE
120 FPS support

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#735]
iPhone 13 Pro and iPad Pro screens can do 90 or 120 FPS but GoMap is capped at 60 FPS

https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro#

**Comment by dieterdreist** [comment]
it's a feature for battery life, so you can map longer...

**Comment by verhovsky** [comment]
you can turn battery saver mode

**Comment by bryceco** [comment]
The number of objects displayed on screen is tuned to allow 60 FPS on older devices. On newer devices we could display more objects, or we could increase frame rate, or as @dieterdreist says we could leave it at 60 to save battery. 

Battery saver isn't great for mapping because it dims the screen and turns off the display more quickly, which is annoying. Does it also reduce frame rate (or can the app ask)?

**Comment by dieterdreist** [comment]
in fairness I must admit I’m currently on iphone7 (for the past 7 or so years) and get 60fps initially but it drops when I move and load more data, to 50 and even 40. For mapping I would consider 5fps sufficient, but I don’t want to step in the way :)

**Comment by bryceco** [comment]
The code does scale the number of objects based on device performance, but it maxes out at around iPhone 7 performance levels so in practice it's now a constant. (Search for references to Geekbench in the code.)

**Comment by bryceco** [comment]
Okay, I've tried setting what are supposed to be the appropriate .plist and CADisplayLink settings but I'm not getting above 60 FPS. Any help from someone smarter?

**Comment by bryceco** [comment]
Added in 32e060fdad4ea1692deaa2ac1026c2296fefd644
