### ISSUE TITLE
Two new resources to add

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#740]
Hello, can EOX Sentinel-2 cloudless 2022 be added to the default list of available aerial imagery?

https://eox.at/2023/10/sentinel-2-cloudless-2022/

WMS link:
https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities

Id also like to suggest using Strava heat map as an overlay
Allowed:
https://lists.openstreetmap.org/pipermail/talk/2019-November/083564.html

Link:
https://proxy.nakarte.me/https/heatmap-external-b.strava.com/tiles-auth/all/red/{zoom}/{x}/{y}.png?px=256

Also apparently replacing “all” with “ride” and “run” will change variant as per this Reddit [post](https://www.reddit.com/r/openstreetmap/comments/19f3xvj/comment/kji7f9l/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
So probably allowing the user to change it may be a good idea

**Comment by bryceco** [comment]
EOX is excluded because we follow the same aerial list as iD/Rapid. See https://github.com/openstreetmap/iD/pull/9807. If you really want to use it you can add it as a custom background.

Strava heat map is excluded because it requires a token to get hi-res imagery. Even though you can use the proxy you mention to access it that probably violates the Strava license agreement, which we don't want to do.
