### ISSUE TITLE
Support of Map Notes

### ISSUE THREAD

**Issue by Skippern** [bryceco/GoMap#75]
It should be possible to add, comment, close and reopen notes in the active screen area. This can be useful for several reasons:

1) do field survey and close out existing notes put by armchair mappers
2) add reminders where tagging/editing is too complex to be done in GoMap, so that they can be actioned with other editors
3) comments to clarify or close out of comments in the area
4) reopen comments that are wrongly closed

**Comment by harry-wood** [comment]
I see the app can add a ['note' tag](http://wiki.openstreetmap.org/wiki/Key:note) (just as another preset field). Potentially useful, and I guess that's why you set this to 'fixed' but...

I think Skippern was talking about [Notes](http://wiki.openstreetmap.org/wiki/Notes). Totally separate type of data the OpenStreetMap API now has.

It would be neat to be able to 'add', 'resolve' & 'comment' on notes from within this app ...or just _viewing_ existing notes in the current area would be neat

**Comment by bryceco** [comment]
It is fixed in the beta that is currently awaiting App Store approval.
