### ISSUE TITLE
Moving a way is very laggy

### ISSUE THREAD

**Issue by Alex-Vasile** [bryceco/GoMap#769]
Moving an individual node is very fast and responsive, but trying to move a way is very laggy and jittery.

Even a simple square will cause serious performance issues when moved. It's noticeable even on a 3 point way, but really starts being noticeable with a rectangle.

**Comment by bryceco** [comment]
This is a long-standing issue. The root cause is because we recompute the quad-tree for every entity that contains the nodes in the way, and we don't have a index of objects containing the node so we iterate over all objects to see what needs to be updated. 

From a user perspective the solution is to clear the cache so we have fewer objects to iterate over. 

I'm working on an update where we track parents of nodes, which is more fragile during edits.

**Comment by Alex-Vasile** [comment]
When you say "we iterate over all objects", do you literally mean **all** cached objects?

Would it be possible to do some spatial partitioning for the caching and searching so the max workload is dictated by the partition size (a constant) rather than the cache size?

Sorry if that's naive and you already do that, I haven't taken a dive into the code base yet.

**Comment by bryceco** [comment]
Yes it really is all objects (or all ways). I agree it would be smarter (and not too much code) to only look at the ways that are currently displayed on screen, which we can grab from the shownObjects array.

**Comment by Alex-Vasile** [comment]
Just tried out on TestFlight. Works beautifully!

**Comment by bryceco** [comment]
Thanks for the nudge, it really helped to get me to reevaluate the approach!
