### ISSUE TITLE
Raster maps on iPad (and maybe Mac) should be zoomed out

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#771]
On iPad having raster base maps on can be really low quality because of it being really zoomed in. But on a phone that has a smaller screen the current zoom looks fine but on a bigger screen, as I said, can look very low quality.
Here are images in go map and the other in osmand
![DF3FD4FF-F1E3-4350-ABBA-17E861FB4F06](https://github.com/bryceco/GoMap/assets/129241633/4a0341d7-6a80-4457-af81-56de91e0ec17)
![937C6002-4F59-457E-9F6A-2C3FD55B37AB](https://github.com/bryceco/GoMap/assets/129241633/0d8ca3c4-2cb1-4f25-ad26-6e2cd4d5789c)

Here is an image where the text looks bad (in full screen)
![F5451A54-060E-458E-958A-4F12F38758CA](https://github.com/bryceco/GoMap/assets/129241633/f91b7f29-0c5d-4033-b2bc-8733f00e7d7b)

This might be an issue on Mac but I don’t know (I don’t own one)

**Comment by bryceco** [comment]
If open the same map at the same zoom level on iPhone and iPad the text is exactly the same, same size and resolution. The screenshot you took of the iPad is at the zoom level just before it transitions to the next higher resolution, so that's the worst-case screenshot, where the text has been magnified by almost a factor of two larger than it's intended size.

If we wanted the text to be crisper we could switch to the higher zoom tiles earlier, but because it's raster all the text labels would be half the size and harder to read. When you start drilling down to minor street names the labels become almost impossible to read when because they're too small. 

So it's basically a trade-off between have crisper text or larger text. Hopefully raster maps will go away soon and we won't have this problem.
