### ISSUE TITLE
Dark Basemap

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#789]
A dark basemap would be great to have as sometimes when I am mapping I would switch to mapnik  then get flash banged by the white colors so I’d really appreciate having a dark basemap. The only thing I could find a dark mode Mapnik was by inserting css code in a [Github issue](https://github.com/openstreetmap/openstreetmap-website/issues/2332#issuecomment-727266980) but I don’t know if that’s possible in an app but at the same time I don’t fully understand what I’m talking about.

**Comment by bryceco** [comment]
I implemented this in a branch, but haven’t merged it because I thought it needed more feedback. One minor nitpick is that white roads are now black, while all other roads are simply darkened:
![image](https://github.com/user-attachments/assets/b2c4f7ff-fb17-48fa-8c09-42989ef29f4b)
![image](https://github.com/user-attachments/assets/d9fe730a-d424-4008-b92f-e6443efb39f4)

**Comment by ooosssay** [comment]
Yeah, the roads look weird but also the buildings and icons may be a little to bright.

**Comment by bryceco** [comment]
That's using the CSS trick, which isn't the best approach when we have the full power of CoreImage available.

I pushed the branch to https://github.com/bryceco/GoMap/tree/dark-mode-basemap if anyone wants to play with it. The color adjustment is done in https://github.com/bryceco/GoMap/blob/dark-mode-basemap/src/Shared/Utility/DarkModeImage.swift

**Comment by bryceco** [comment]
This is just reducing the brightness (-40%) of the image:

![image](https://github.com/user-attachments/assets/2d8610cd-8825-4d88-90bd-2b3c0eae3556)

**Comment by ooosssay** [comment]
Yeah at that brightness the icons should be good

**Comment by bryceco** [comment]
Fixed in 1e5ee9f1f350cfef9c7fdba3eee1f91b85d4f455
