### ISSUE TITLE
Americana bugs 

### ISSUE THREAD

**Issue by ooosssay** [bryceco/GoMap#799]
Administrative borders have () running alongside them 
![IMG_7520](https://github.com/user-attachments/assets/f8ff9f3e-1e9a-4e6a-bf2e-693a70444626)

Additionally, when the user zooms all the way out, the movement of the map becomes buggy. The Americana map should possibly have a max zoom restriction to avoid this. 

https://github.com/user-attachments/assets/d4b307ac-a1d6-440c-8b8d-bfbeb06bdaba

**Comment by bryceco** [comment]
I agree these are both real bugs, but I don't think there's not much we can do about them. Limiting zooming helps make the second issue less noticeable but you can still see it close to the poles even when zoomed in.

**Comment by 1ec5** [comment]
> Administrative borders have () running alongside them

Huh, this comes from the boundary edge labels, which normally contain country names. OpenMapTiles provides ISO&nbsp;3166-1 alpha-3 country codes; at runtime, the OSM Americana application maps them to localized country names using a lookup table. Since Go Map!! uses the raw style, the lookup table is empty, but this expression is supposed to fall back to the country code in parentheses:

https://github.com/ZeLonewolf/openstreetmap-americana/blob/0d51830b14a4abe962d345aeb4cd7ff3edd118ec/src/layer/boundary.js#L315

None of this should be relevant. I have no idea why it’s trying to label subnational boundaries.

**Comment by bryceco** [comment]
I knew you would have some insight into this. And I was also pretty sure the explanation would be something beyond our control 🙃. Is there any chance the localization affects this?

**Comment by 1ec5** [comment]
The lookup table is injected at runtime using the same mechanism as localized labels. But the stylesheet is only supposed to be labeling `admin_level=2` boundaries anyways, not these `admin_level=4` boundaries.
