### ISSUE TITLE
Searching for a feature should select it

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#810]
I search for a feature

![image](https://github.com/user-attachments/assets/bd855b53-cd26-4048-bf86-fbb9bd70ec54)

but when I select it it's not selected so I can't actually edit it

![image](https://github.com/user-attachments/assets/86549072-edbe-4d66-8778-75db9abd7c04)

**Comment by bryceco** [comment]
Yeah, we should ensure that some portion of the object is on-screen and also select it. 

There's a method `latLonOnObject(forLatLon` that will convert the midpoint we currently zoom to into a point on the object itself.

**Comment by bryceco** [comment]
Turns out this is more complicated than expected. We can query Nominatim for the object and get its location and OSM ID, and we can jump to that location, but we can't select the object until the object data has been downloaded. This can happen an arbitrarily long time later, or might not happen at all (depending on network conditions). And we don't have a mechanism to generate a callback when a particular object gets downloaded. 

I've updated the code to ensure that we jump to a location where a node belonging to the object is centered  (instead of the center of the object), which I think is enough to solve the problematic situations.
