### ISSUE TITLE
Disable dark-mode basemap

### ISSUE THREAD

**Issue by upintheairsheep** [bryceco/GoMap#813]
Hello, can you add an option to disable the altered dark mode base maps, for example Mapnik? It may be helpful for some users, but the low-quality dithering makes it unfavorable for others.

**Comment by bryceco** [comment]
What do you mean by low-quality dithering? It shouldn't be changing the resolution.

**Comment by upintheairsheep** [comment]
> What do you mean by low-quality dithering? It shouldn't be changing the resolution.
Not dithering, but it just looks a bit unclean compared to normal Mapnik/etc.
![86039B92-A673-4019-B8D9-6480F68EA5EB](https://github.com/user-attachments/assets/6655a8da-9caa-44a5-8313-4173c60272ec)

**Comment by bryceco** [comment]
Long-time commentators know I don't like configuration options, so if the brightness level is inappropriate we should fix it, rather than provide an option to disable it. 

I don't use DarkMode myself so I'd prefer the community decide on a level of dimming that is agreeable to everyone. Currently it is set at -40% (or 60%) brightness. There are various online tools that will show you what other brightness levels look like (you can upload screenshots). Could you post examples of what you like and we can get comments from other users?

**Comment by verhovsky** [comment]
It's not the amount of brightness, but that whatever you're doing to invert the colors is making text look bad, probably because it affects the blurriness around letters ("dithering") somehow, though admittedly it's already bad because open street map renders the map at half resolution to save money and looks terribly blurry on modern high pixel density displays.

![image](https://github.com/user-attachments/assets/4a0170fe-81c3-42c9-91be-e389d787ff4d)

![image](https://github.com/user-attachments/assets/4e344c80-19d3-430d-8e53-8ae20b7affb7)

**Comment by bryceco** [comment]
It's using a CoreImage filter that adjusts the brightness and nothing else, but that exposes the graininess of the underlying image.
