### ISSUE TITLE
Add year of imagery

### ISSUE THREAD

**Issue by verhovsky** [bryceco/GoMap#814]
I would like to know when the satellite imagery I'm looking at was taken.

Google Maps solves this in a great way, it just says "(c) 2021 Google" in the corner. iD gives you a setting that draws a bright red grid over the entire map and labels each square with a year, this is an awful design because it's behind a setting and super intrusive so I never use it even though I want to know all the time, it's just too much work.

So my suggestion is in the top left you should say like "2021 Bing" or "2021 Microsoft" if that's right. I think it should be the year of the newest image currently in the viewport, although you could also argue for the oldest.

You should also clean up the top left because it's way too busy. Why does it say "Bing" twice and have both "Microsoft" and the Microsoft logo. Also does it really need to say "Aerial"? I can see that it's Aerial imagery. Just "2021 Bing" would be fine, users can click on it for more info.

![image](https://github.com/user-attachments/assets/0a14385f-c7d0-426a-9e53-6306b8d62eca)

**Comment by bryceco** [comment]
Clicking the Bing logo is supposed to show a pop-up displaying the year(s) of the imagery, but it appears that is broken at the moment. That only works for Bing because other providers don't have an API to retrieve that information. 

For all aerial providers we show their logo (if we have one) and the name of the imagery. It just happens that for Microsoft both are long and verbose. We could special-case some of the common imagery providers.

**Comment by bryceco** [comment]
Clicking the Bing logo seems to be working for me now. Not sure what the problem was before.

**Comment by bryceco** [comment]
ee49f1994babf484f572263a514e47aca3de0edb
